-- TASK: TEMP.JUSDAVIS.TASK_COMPUTE_COMPOSITE_PATTERNS  |  created: 2026-04-08 18:19:49.854000+00:00

create or replace task TASK_COMPUTE_COMPOSITE_PATTERNS
	warehouse=SE_XS_WH
	after TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_ONT_ACCOUNT_SIGNALS
	as CALL TEMP.JUSDAVIS.SP_COMPUTE_COMPOSITE_PATTERNS();
