-- TASK: TEMP.JUSDAVIS.TASK_COMPUTE_ACCOUNT_BRIEFINGS  |  created: 2026-04-08 18:32:53.932000+00:00

create or replace task TASK_COMPUTE_ACCOUNT_BRIEFINGS
	warehouse=SE_XS_WH
	schedule='USING CRON 0 6 * * * UTC'
	as CALL TEMP.JUSDAVIS.SP_COMPUTE_ACCOUNT_BRIEFINGS();
