-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_ONT_ACCOUNT_COMPETITORS  |  created: 2026-04-06 18:48:46.882000+00:00

create or replace task TASK_REFRESH_BKMNG_ONT_ACCOUNT_COMPETITORS
	warehouse=SE_XS_WH
	schedule='USING CRON 20 */2 * * * UTC'
	COMMENT='Refresh ONT_ACCOUNT_COMPETITORS every 2 hours at :20'
	as CALL TEMP.JUSDAVIS.SP_REFRESH_BKMNG_ONT_ACCOUNT_COMPETITORS();
