-- TASK: TEMP.JUSDAVIS.TASK_COMPUTE_SUPPORT_SIGNALS  |  created: 2026-04-07 22:00:41.684000+00:00

create or replace task TASK_COMPUTE_SUPPORT_SIGNALS
	warehouse=SE_XS_WH
	schedule='USING CRON 50 * * * * UTC'
	as CALL TEMP.JUSDAVIS.SP_COMPUTE_SUPPORT_SIGNALS();
