-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_SUPPORT_TICKETS  |  created: 2026-04-07 21:58:27.718000+00:00

create or replace task TASK_REFRESH_BKMNG_SUPPORT_TICKETS
	warehouse=SE_XS_WH
	schedule='USING CRON 45 * * * * UTC'
	as CALL TEMP.JUSDAVIS.SP_REFRESH_BKMNG_SUPPORT_TICKETS();
