-- TASK: TEMP.JUSDAVIS.TASK_PARSE_BKMNG_USE_CASE_NOTES  |  created: 2026-04-07 16:36:55.414000+00:00

create or replace task TASK_PARSE_BKMNG_USE_CASE_NOTES
	warehouse=SE_XS_WH
	after TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_USE_CASES
	as CALL TEMP.JUSDAVIS.SP_PARSE_BKMNG_USE_CASE_NOTES();
