-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_ACEM_TEAM  |  created: 2026-04-04 06:12:02.594000+00:00

create or replace task TASK_REFRESH_BKMNG_ACEM_TEAM
	warehouse=SE_XS_WH
	schedule='USING CRON 2 */4 * * * UTC'
	as BEGIN
    TRUNCATE TABLE TEMP.JUSDAVIS.BKMNG_ACEM_TEAM;
    INSERT INTO TEMP.JUSDAVIS.BKMNG_ACEM_TEAM (ACEM_EMAIL, ACE_EMAIL, REFRESHED_AT)
    SELECT DISTINCT
        mgr.EMAIL,
        a.ACE_ASSIGNED,
        CURRENT_TIMESTAMP()
    FROM TEMP.JUSDAVIS.BKMNG_ACCOUNTS a
    INNER JOIN FIVETRAN.SALESFORCE.USER u
        ON u.EMAIL = a.ACE_ASSIGNED
        AND u._FIVETRAN_DELETED = FALSE
    INNER JOIN FIVETRAN.SALESFORCE.USER mgr
        ON mgr.ID = u.MANAGER_ID
        AND mgr._FIVETRAN_DELETED = FALSE;
END;
