-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_SECURITY_POSTURE  |  created: 2026-04-16 19:36:47.732000+00:00

create or replace task TASK_REFRESH_BKMNG_SECURITY_POSTURE
	warehouse=SE_XS_WH
	schedule='USING CRON 0 5 * * * UTC'
	as CALL TEMP.JUSDAVIS.SP_REFRESH_BKMNG_SECURITY_POSTURE();
