-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_USE_CASES  |  created: 2026-04-15 20:14:16.199000+00:00

create or replace task TASK_REFRESH_BKMNG_USE_CASES
	warehouse=SE_XS_WH
	schedule='USING CRON 5 */4 * * * UTC'
	as BEGIN
    TRUNCATE TABLE TEMP.JUSDAVIS.BKMNG_USE_CASES;
    INSERT INTO TEMP.JUSDAVIS.BKMNG_USE_CASES (
        USE_CASE_ID, ACCOUNT_ID, ACCOUNT_NAME, USE_CASE_NAME, DESCRIPTION,
        STATUS, STAGE, COMPLEXITY, GO_LIVE_DATE, TARGET_GO_LIVE_DATE,
        DECISION_DATE, LEAD_SE, ACE_ASSIGNED, CREATED_DATE, LAST_MODIFIED_DATE,
        NOTES, PS_NOTES_SUMMARY,
        MEDDPICC_OVERALL_SCORE, MEDDPICC_METRICS_SCORE, MEDDPICC_METRICS,
        MEDDPICC_ECONOMIC_BUYER_SCORE, MEDDPICC_ECONOMIC_BUYER,
        MEDDPICC_DECISION_CRITERIA_SCORE, MEDDPICC_DECISION_CRITERIA,
        MEDDPICC_DECISION_PROCESS_SCORE, MEDDPICC_DECISION_PROCESS,
        MEDDPICC_IDENTIFY_PAIN_SCORE, MEDDPICC_IDENTIFY_PAIN,
        MEDDPICC_CHAMPION_SCORE, MEDDPICC_CHAMPION,
        MEDDPICC_COMPETITOR_SCORE, MEDDPICC_COMPETITORS,
        IMPLEMENTATION_START_DATE,
        REFRESHED_AT
    )
    SELECT
        uc.ID,
        uc.ACCOUNT_C,
        acc.ACCOUNT_NAME,
        COALESCE(uc.NAME_C, uc.NAME),
        NULL,
        uc.USE_CASE_STATUS_C,
        uc.STAGE_C,
        NULL,
        uc.ACTUAL_GO_LIVE_DATE_C,
        NULL,
        uc.DECISION_DATE_C,
        lse.EMAIL,
        acc.ACE_ASSIGNED,
        uc.CREATED_DATE,
        CONVERT_TIMEZONE('UTC', uc.LAST_MODIFIED_DATE)::TIMESTAMP_NTZ,
        LEFT(NULLIF(ARRAY_TO_STRING(ARRAY_COMPACT(ARRAY_CONSTRUCT(
            NULLIF(TRIM(uc.USE_CASE_COMMENTS_C), ''),
            NULLIF(TRIM(uc.IMPLEMENTATION_COMMENTS_C), '')
        )), ' | '), ''), 32768) AS NOTES,
        IFF(
            NULLIF(ARRAY_TO_STRING(ARRAY_COMPACT(ARRAY_CONSTRUCT(
                NULLIF(TRIM(uc.USE_CASE_COMMENTS_C), ''),
                NULLIF(TRIM(uc.IMPLEMENTATION_COMMENTS_C), '')
            )), ' | '), '') IS NOT NULL,
            LEFT(SNOWFLAKE.CORTEX.SUMMARIZE(
                LEFT(NULLIF(ARRAY_TO_STRING(ARRAY_COMPACT(ARRAY_CONSTRUCT(
                    NULLIF(TRIM(uc.USE_CASE_COMMENTS_C), ''),
                    NULLIF(TRIM(uc.IMPLEMENTATION_COMMENTS_C), '')
                )), ' | '), ''), 8000)
            ), 4000),
            NULL
        ) AS PS_NOTES_SUMMARY,
        uc.OVERALL_SCORE_C,
        uc.METRICS_SCORE_C,
        LEFT(uc.MEDDPICC_METRICS_C, 16384),
        uc.ECONOMIC_BUYER_SCORE_C,
        eb_c.NAME,
        uc.DECISION_CRITERIA_SCORE_C,
        LEFT(uc.MEDDPICC_DECISION_CRITERIA_C, 16384),
        uc.DECISION_PROCESS_SCORE_C,
        LEFT(uc.MEDDPICC_DECISION_PROCESS_C, 16384),
        uc.IDENTIFY_PAIN_SCORE_C,
        LEFT(uc.MEDDPICC_IDENTIFY_PAIN_C, 16384),
        uc.CHAMPION_SCORE_C,
        champ_c.NAME,
        uc.COMPETITOR_SCORE_C,
        uc.COMPETITORS_C,
        uc.IMPLEMENTATION_START_DATE_C,
        CURRENT_TIMESTAMP()
    FROM FIVETRAN.SALESFORCE.USE_CASE_C uc
    INNER JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS acc
        ON acc.ACCOUNT_ID = uc.ACCOUNT_C
    LEFT JOIN FIVETRAN.SALESFORCE.USER lse
        ON lse.ID = uc.LEAD_SALES_ENGINEER_C
        AND lse._FIVETRAN_DELETED = FALSE
    LEFT JOIN FIVETRAN.SALESFORCE.CONTACT eb_c
        ON eb_c.ID = uc.MEDDPICC_ECONOMIC_BUYER_C
        AND eb_c.IS_DELETED = FALSE
    LEFT JOIN FIVETRAN.SALESFORCE.CONTACT champ_c
        ON champ_c.ID = uc.MEDDPICC_CHAMPION_C
        AND champ_c.IS_DELETED = FALSE
    WHERE uc.IS_DELETED = FALSE;
END;
