-- TASK: TEMP.JUSDAVIS.TASK_COMPUTE_USE_CASE_BREAKDOWNS  |  created: 2026-04-15 21:28:59.520000+00:00

create or replace task TASK_COMPUTE_USE_CASE_BREAKDOWNS
	warehouse=SE_XS_WH
	after TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_USE_CASES
	as CALL TEMP.JUSDAVIS.SP_COMPUTE_USE_CASE_BREAKDOWNS(TRUE);
