-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_TMRS  |  created: 2026-04-06 15:18:16.231000+00:00

create or replace task TASK_REFRESH_BKMNG_TMRS
	warehouse=SE_XS_WH
	schedule='USING CRON 30 * * * * UTC'
	as BEGIN
  TRUNCATE TABLE TEMP.JUSDAVIS.BKMNG_TMRS;
  INSERT INTO TEMP.JUSDAVIS.BKMNG_TMRS (
    TMR_ID, ACCOUNT_ID, ACCOUNT_NAME, STATUS, SPECIALIST_TYPE,
    ACTIVITY_REQUESTED, ENGAGEMENT_TYPE, REQUESTOR, REQUESTOR_EMAIL,
    REQUESTED_DATE, ASSIGNED_RESOURCE_ID, ASSIGNED_RESOURCE_EMAIL, ASSIGNED_RESOURCE_NAME,
    SECONDARY_MEMBER_ID, SECONDARY_MEMBER_EMAIL, SECONDARY_MEMBER_NAME,
    SPECIALIST_COMMENTS, REQUEST_REASON, MANAGER_APPROVER_ID, MANAGER_APPROVER_EMAIL,
    CLOSE_DATE, START_DATE, REFRESHED_AT
  )
  SELECT
    t.ID,
    t.ACCOUNT_ID,
    a.ACCOUNT_NAME,
    t.STATUS,
    t.SPECIALIST_TYPE,
    t.ACTIVITY_REQUESTED,
    t.ENGAGEMENT_TYPE,
    t.CREATED_BY_NAME,
    t.CREATED_BY_EMAIL,
    t.REQUEST_CREATED_DATE::DATE,
    t.ASSIGNED_RESOURCE_ID,
    res.EMAIL,
    res.NAME,
    t.SECONDARY_ASSIGNED_TEAM_MEMBER,
    sec.EMAIL,
    sec.NAME,
    LEFT(t.SPECIALIST_COMMENTS, 4000),
    LEFT(t.REQUEST_REASON, 2000),
    t.MANAGER_APPROVER,
    mgr.EMAIL,
    t.REQUEST_CLOSE_DATE::DATE,
    t.TARGET_ACTIVITY_START_DATE::DATE,
    CURRENT_TIMESTAMP()
  FROM SALES.SALES_ENGINEERING.FIELD_SPECIALIST_REQUESTS_DX_ELEMENTUM t
  JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS a ON a.ACCOUNT_ID = t.ACCOUNT_ID
  LEFT JOIN FIVETRAN.SALESFORCE.USER res
    ON res.ID = t.ASSIGNED_RESOURCE_ID AND NOT res._FIVETRAN_DELETED
  LEFT JOIN FIVETRAN.SALESFORCE.USER sec
    ON sec.ID = t.SECONDARY_ASSIGNED_TEAM_MEMBER AND NOT sec._FIVETRAN_DELETED
  LEFT JOIN FIVETRAN.SALESFORCE.USER mgr
    ON mgr.ID = t.MANAGER_APPROVER AND NOT mgr._FIVETRAN_DELETED
  WHERE t.SPECIALIST_TYPE = 'Account Engineer';
END;
