-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_ONT_OPPORTUNITIES  |  created: 2026-04-06 18:48:47.536000+00:00

create or replace task TASK_REFRESH_BKMNG_ONT_OPPORTUNITIES
	warehouse=SE_XS_WH
	schedule='USING CRON 45 1 * * * UTC'
	COMMENT='Refresh ONT_OPPORTUNITIES daily at 01:45 UTC'
	as CALL TEMP.JUSDAVIS.SP_REFRESH_BKMNG_ONT_OPPORTUNITIES();
