-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_MEETING_ACTIVITY  |  created: 2026-04-08 01:24:28.394000+00:00

create or replace task TASK_REFRESH_BKMNG_MEETING_ACTIVITY
	warehouse=SE_XS_WH
	schedule='USING CRON 0 3 * * * UTC'
	as CALL TEMP.JUSDAVIS.SP_REFRESH_BKMNG_MEETING_ACTIVITY();
