-- TASK: TEMP.JUSDAVIS.TASK_COMPUTE_AI_ASSESSMENTS  |  created: 2026-04-07 23:57:00.769000+00:00

create or replace task TASK_COMPUTE_AI_ASSESSMENTS
	warehouse=SE_XS_WH
	schedule='USING CRON 0 6 * * * UTC'
	COMMENT='Daily AI assessment computation via CORTEX.COMPLETE'
	as CALL TEMP.JUSDAVIS.SP_COMPUTE_AI_ASSESSMENTS();
