-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_ONT_CONTACTS  |  created: 2026-04-06 18:48:47.300000+00:00

create or replace task TASK_REFRESH_BKMNG_ONT_CONTACTS
	warehouse=SE_XS_WH
	schedule='USING CRON 30 1 * * * UTC'
	COMMENT='Refresh ONT_CONTACTS daily at 01:30 UTC'
	as CALL TEMP.JUSDAVIS.SP_REFRESH_BKMNG_ONT_CONTACTS();
