-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_USER_ALERTS  |  created: 2026-04-07 21:09:52.159000+00:00

create or replace task TASK_REFRESH_BKMNG_USER_ALERTS
	warehouse=SE_XS_WH
	after TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_ONT_ACCOUNT_SIGNALS
	as CALL TEMP.JUSDAVIS.SP_REFRESH_BKMNG_USER_ALERTS();
