-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_GONG_CALLS  |  created: 2026-04-06 15:17:14.209000+00:00

create or replace task TASK_REFRESH_BKMNG_GONG_CALLS
	warehouse=SE_XS_WH
	schedule='USING CRON 0 */2 * * * UTC'
	as BEGIN
  TRUNCATE TABLE TEMP.JUSDAVIS.BKMNG_GONG_CALLS;
  INSERT INTO TEMP.JUSDAVIS.BKMNG_GONG_CALLS (
    CALL_ID, ACCOUNT_ID, ACCOUNT_NAME, TITLE, CALL_DATE, DURATION_MINS,
    TOPICS, NEXT_STEPS, RECORDING_URL, PARTICIPANTS, SUMMARY, KEY_POINTS, REFRESHED_AT
  )
  SELECT
    g.ID,
    g.GONG_PRIMARY_ACCOUNT_C,
    a.ACCOUNT_NAME,
    g.GONG_TITLE_C,
    g.GONG_CALL_START_C::TIMESTAMP_NTZ,
    FLOOR(g.GONG_CALL_DURATION_SEC_C / 60),
    LEFT(g.GONG_RELATED_TOPICS_JSON_C, 4000),
    LEFT(g.GONG_CALL_HIGHLIGHTS_NEXT_STEPS_C, 4000),
    g.GONG_VIEW_CALL_C,
    LEFT(g.GONG_PARTICIPANTS_EMAILS_C, 2000),
    LEFT(g.GONG_CALL_BRIEF_C, 4000),
    LEFT(g.GONG_CALL_KEY_POINTS_C, 4000),
    CURRENT_TIMESTAMP()
  FROM FIVETRAN.SALESFORCE.GONG_GONG_CALL_C g
  JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS a ON a.ACCOUNT_ID = g.GONG_PRIMARY_ACCOUNT_C
  WHERE g.GONG_CALL_START_C >= DATEADD('day', -90, CURRENT_TIMESTAMP())
    AND g.GONG_PRIMARY_ACCOUNT_C IS NOT NULL;
END;
