-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_ONT_INTERACTIONS  |  created: 2026-04-06 18:48:46.308000+00:00

create or replace task TASK_REFRESH_BKMNG_ONT_INTERACTIONS
	warehouse=SE_XS_WH
	schedule='USING CRON 15 */2 * * * UTC'
	COMMENT='Refresh ONT_INTERACTIONS every 2 hours at :15'
	as CALL TEMP.JUSDAVIS.SP_REFRESH_BKMNG_ONT_INTERACTIONS();
