-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_ONT_USE_CASES  |  created: 2026-04-06 18:48:48.570000+00:00

create or replace task TASK_REFRESH_BKMNG_ONT_USE_CASES
	warehouse=SE_XS_WH
	schedule='USING CRON 30 */4 * * * UTC'
	COMMENT='Refresh ONT_USE_CASES every 4 hours at :30'
	as CALL TEMP.JUSDAVIS.SP_REFRESH_BKMNG_ONT_USE_CASES();
