-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_SECURITY_SIGNALS  |  created: 2026-04-16 19:55:32.265000+00:00

create or replace task TASK_REFRESH_BKMNG_SECURITY_SIGNALS
	warehouse=SE_XS_WH
	after TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_SECURITY_POSTURE
	as CALL TEMP.JUSDAVIS.SP_REFRESH_BKMNG_SECURITY_SIGNALS();
