-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_ACCOUNTS  |  created: 2026-04-10 17:30:08.047000+00:00

create or replace task TASK_REFRESH_BKMNG_ACCOUNTS
	warehouse=SE_XS_WH
	schedule='USING CRON 0 */4 * * * UTC'
	as BEGIN
    TRUNCATE TABLE TEMP.JUSDAVIS.BKMNG_ACCOUNTS;
    INSERT INTO TEMP.JUSDAVIS.BKMNG_ACCOUNTS (
        ACCOUNT_ID, ACCOUNT_NAME, INDUSTRY, REGION,
        ACE_USER_ID, ACE_ASSIGNED,
        LEAD_SE_EMAIL, AE_EMAIL, AE_NAME,
        ENGAGEMENT_STATUS, STATUS,
        ACTIVATION_START_DATE, TOTAL_CREDITS_ALLOCATED,
        ACV, CONSUMPTION_YTD, REFRESHED_AT
    )
    SELECT
        a.ID,
        a.NAME,
        a.INDUSTRY,
        a.REGION_C,
        atm.USER_ID,
        u.EMAIL                             AS ACE_ASSIGNED,
        lse.EMAIL                           AS LEAD_SE_EMAIL,
        ao.EMAIL                            AS AE_EMAIL,
        ao.NAME                             AS AE_NAME,
        'Normal'                            AS ENGAGEMENT_STATUS,
        'active'                            AS STATUS,
        NULL, NULL,
        a.ACCOUNT_BASE_RENEWAL_ACV_C,
        a.ACTUAL_CONSUMPTION_YTD_C,
        CURRENT_TIMESTAMP()
    FROM FIVETRAN.SALESFORCE.ACCOUNT a
    INNER JOIN FIVETRAN.SALESFORCE.ACCOUNT_TEAM_MEMBER atm
        ON atm.ACCOUNT_ID = a.ID
        AND atm.TEAM_MEMBER_ROLE = 'SE - Activation'
        AND atm.IS_DELETED = FALSE
    INNER JOIN FIVETRAN.SALESFORCE.USER u
        ON u.ID = atm.USER_ID
        AND u._FIVETRAN_DELETED = FALSE
    LEFT JOIN FIVETRAN.SALESFORCE.USER lse
        ON lse.ID = a.LEAD_SALES_ENGINEER_C
        AND lse._FIVETRAN_DELETED = FALSE
    LEFT JOIN FIVETRAN.SALESFORCE.USER ao
        ON ao.ID = a.OWNER_ID
        AND ao._FIVETRAN_DELETED = FALSE
    LEFT JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNT_SETTINGS s
        ON s.ACCOUNT_ID = a.ID
    WHERE a.IS_DELETED = FALSE
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY a.ID
        ORDER BY CASE WHEN LOWER(u.EMAIL) = LOWER(s.PRIMARY_ACE_EMAIL) THEN 0 ELSE 1 END,
                 u.EMAIL
    ) = 1;
END;
