-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_ONT_ACCOUNTS  |  created: 2026-04-06 18:48:47.741000+00:00

create or replace task TASK_REFRESH_BKMNG_ONT_ACCOUNTS
	warehouse=SE_XS_WH
	schedule='USING CRON 25 */4 * * * UTC'
	COMMENT='Refresh ONT_ACCOUNTS every 4 hours at :25'
	as CALL TEMP.JUSDAVIS.SP_REFRESH_BKMNG_ONT_ACCOUNTS();
