-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_ONT_ACCOUNT_SIGNALS  |  created: 2026-04-06 18:48:49.378000+00:00

create or replace task TASK_REFRESH_BKMNG_ONT_ACCOUNT_SIGNALS
	warehouse=SE_XS_WH
	schedule='USING CRON 0 * * * * UTC'
	COMMENT='Refresh ONT_ACCOUNT_SIGNALS every hour at :00'
	as CALL TEMP.JUSDAVIS.SP_REFRESH_BKMNG_ONT_ACCOUNT_SIGNALS();
