-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_UNIFIED_MEETINGS
-- Task 5: runs SP_REFRESH_BKMNG_UNIFIED_MEETINGS every 2h (replaces gong_calls + meeting_activity tasks)

CREATE OR REPLACE TASK TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_UNIFIED_MEETINGS
    WAREHOUSE = SE_XS_WH
    SCHEDULE = 'USING CRON 0 */2 * * * UTC'
    AS CALL TEMP.JUSDAVIS.SP_REFRESH_BKMNG_UNIFIED_MEETINGS();
