-- TASK: TEMP.JUSDAVIS.TASK_REFRESH_BKMNG_EMAIL_ACTIVITY  |  created: 2026-04-08 01:24:29.655000+00:00

create or replace task TASK_REFRESH_BKMNG_EMAIL_ACTIVITY
	warehouse=SE_XS_WH
	schedule='USING CRON 0 2 * * * UTC'
	as CALL TEMP.JUSDAVIS.SP_REFRESH_BKMNG_EMAIL_ACTIVITY();
