-- PROCEDURE: TEMP.JUSDAVIS.SP_BKMNG_PIPELINE_INVENTORY()
-- Returns a snapshot of all tasks in TEMP.JUSDAVIS with state, schedule, predecessors,
-- last suspension info, and a 200-char definition preview. Built from SHOW TASKS + RESULT_SCAN.

CREATE OR REPLACE PROCEDURE TEMP.JUSDAVIS.SP_BKMNG_PIPELINE_INVENTORY()
RETURNS TABLE (
  TASK_NAME VARCHAR,
  STATE VARCHAR,
  SCHEDULE VARCHAR,
  WAREHOUSE VARCHAR,
  PREDECESSORS VARCHAR,
  LAST_SUSPENDED_ON VARCHAR,
  LAST_SUSPENDED_REASON VARCHAR,
  DEFINITION_PREVIEW VARCHAR
)
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  res RESULTSET;
BEGIN
  SHOW TASKS IN SCHEMA TEMP.JUSDAVIS;
  res := (
    SELECT
      TO_VARCHAR("name") AS TASK_NAME,
      TO_VARCHAR("state") AS STATE,
      COALESCE(TO_VARCHAR("schedule"), '(predecessor-driven)') AS SCHEDULE,
      TO_VARCHAR("warehouse") AS WAREHOUSE,
      TO_VARCHAR("predecessors") AS PREDECESSORS,
      TO_VARCHAR("last_suspended_on") AS LAST_SUSPENDED_ON,
      TO_VARCHAR("last_suspended_reason") AS LAST_SUSPENDED_REASON,
      LEFT(TO_VARCHAR("definition"), 200) AS DEFINITION_PREVIEW
    FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
    ORDER BY "name"
  );
  RETURN TABLE(res);
END;
$$;
