-- PROCEDURE: TEMP.JUSDAVIS.SP_BKMNG_PIPELINE_HEALTH_CHECK()  |  created: 2026-04-15 22:50:20.781000+00:00

CREATE OR REPLACE PROCEDURE "SP_BKMNG_PIPELINE_HEALTH_CHECK"()
RETURNS TABLE ("TABLE_NAME" VARCHAR, "TS_COLUMN" VARCHAR, "LAST_REFRESH" VARCHAR, "ROW_COUNT" NUMBER(38,0), "AGE_HOURS" NUMBER(38,0), "MAX_AGE_HOURS" NUMBER(38,0), "STATUS" VARCHAR)
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
    res RESULTSET;
BEGIN
    res := (
        WITH checks AS (
            SELECT ''BKMNG_ACCOUNTS'' AS t, ''REFRESHED_AT'' AS c, 8 AS max_h
            UNION ALL SELECT ''BKMNG_ACEM_TEAM'', ''REFRESHED_AT'', 8
            UNION ALL SELECT ''BKMNG_A360_CONTRACT'', ''REFRESHED_AT'', 26
            UNION ALL SELECT ''BKMNG_A360_CONSUMPTION'', ''REFRESHED_AT'', 26
            UNION ALL SELECT ''BKMNG_A360_PRODUCT_ADOPTION'', ''REFRESHED_AT'', 26
            UNION ALL SELECT ''BKMNG_GONG_CALLS'', ''REFRESHED_AT'', 4
            UNION ALL SELECT ''BKMNG_TMRS'', ''REFRESHED_AT'', 2
            UNION ALL SELECT ''BKMNG_SUPPORT_TICKETS'', ''REFRESHED_AT'', 2
            UNION ALL SELECT ''BKMNG_USE_CASES'', ''REFRESHED_AT'', 8
            UNION ALL SELECT ''BKMNG_USE_CASE_NOTES'', ''REFRESHED_AT'', 8
            UNION ALL SELECT ''BKMNG_USE_CASE_BREAKDOWNS'', ''REFRESHED_AT'', 8
            UNION ALL SELECT ''BKMNG_MEETING_ACTIVITY'', ''REFRESHED_AT'', 26
            UNION ALL SELECT ''BKMNG_EMAIL_ACTIVITY'', ''REFRESHED_AT'', 26
            UNION ALL SELECT ''BKMNG_ONT_ACCOUNTS'', ''ONT_REFRESHED_AT'', 8
            UNION ALL SELECT ''BKMNG_ONT_USE_CASES'', ''ONT_REFRESHED_AT'', 8
            UNION ALL SELECT ''BKMNG_ONT_CONTACTS'', ''REFRESHED_AT'', 26
            UNION ALL SELECT ''BKMNG_ONT_INTERACTIONS'', ''REFRESHED_AT'', 4
            UNION ALL SELECT ''BKMNG_ONT_OPPORTUNITIES'', ''REFRESHED_AT'', 26
            UNION ALL SELECT ''BKMNG_ONT_ACCOUNT_SIGNALS'', ''CREATED_AT'', 2
            UNION ALL SELECT ''BKMNG_ONT_ACCOUNT_TOPICS'', ''REFRESHED_AT'', 4
            UNION ALL SELECT ''BKMNG_ONT_ACCOUNT_COMPETITORS'', ''REFRESHED_AT'', 4
            UNION ALL SELECT ''BKMNG_AI_ACCOUNT_ASSESSMENTS'', ''REFRESHED_AT'', 26
            UNION ALL SELECT ''BKMNG_AI_USE_CASE_ASSESSMENTS'', ''REFRESHED_AT'', 26
            UNION ALL SELECT ''BKMNG_COMPOSITE_PATTERNS'', ''CREATED_AT'', 2
            UNION ALL SELECT ''BKMNG_USER_ALERTS'', ''CREATED_AT'', 2
        ),
        actuals AS (
            SELECT ''BKMNG_ACCOUNTS'' AS t, MAX(REFRESHED_AT)::VARCHAR AS lr, COUNT(*) AS cnt FROM TEMP.JUSDAVIS.BKMNG_ACCOUNTS
            UNION ALL SELECT ''BKMNG_ACEM_TEAM'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_ACEM_TEAM
            UNION ALL SELECT ''BKMNG_A360_CONTRACT'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_A360_CONTRACT
            UNION ALL SELECT ''BKMNG_A360_CONSUMPTION'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_A360_CONSUMPTION
            UNION ALL SELECT ''BKMNG_A360_PRODUCT_ADOPTION'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_A360_PRODUCT_ADOPTION
            UNION ALL SELECT ''BKMNG_GONG_CALLS'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_GONG_CALLS
            UNION ALL SELECT ''BKMNG_TMRS'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_TMRS
            UNION ALL SELECT ''BKMNG_SUPPORT_TICKETS'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_SUPPORT_TICKETS
            UNION ALL SELECT ''BKMNG_USE_CASES'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_USE_CASES
            UNION ALL SELECT ''BKMNG_USE_CASE_NOTES'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_USE_CASE_NOTES
            UNION ALL SELECT ''BKMNG_USE_CASE_BREAKDOWNS'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_USE_CASE_BREAKDOWNS
            UNION ALL SELECT ''BKMNG_MEETING_ACTIVITY'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_MEETING_ACTIVITY
            UNION ALL SELECT ''BKMNG_EMAIL_ACTIVITY'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_EMAIL_ACTIVITY
            UNION ALL SELECT ''BKMNG_ONT_ACCOUNTS'', MAX(ONT_REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNTS
            UNION ALL SELECT ''BKMNG_ONT_USE_CASES'', MAX(ONT_REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_ONT_USE_CASES
            UNION ALL SELECT ''BKMNG_ONT_CONTACTS'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_ONT_CONTACTS
            UNION ALL SELECT ''BKMNG_ONT_INTERACTIONS'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_ONT_INTERACTIONS
            UNION ALL SELECT ''BKMNG_ONT_OPPORTUNITIES'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_ONT_OPPORTUNITIES
            UNION ALL SELECT ''BKMNG_ONT_ACCOUNT_SIGNALS'', MAX(CREATED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNT_SIGNALS
            UNION ALL SELECT ''BKMNG_ONT_ACCOUNT_TOPICS'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNT_TOPICS
            UNION ALL SELECT ''BKMNG_ONT_ACCOUNT_COMPETITORS'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNT_COMPETITORS
            UNION ALL SELECT ''BKMNG_AI_ACCOUNT_ASSESSMENTS'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_AI_ACCOUNT_ASSESSMENTS
            UNION ALL SELECT ''BKMNG_AI_USE_CASE_ASSESSMENTS'', MAX(REFRESHED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_AI_USE_CASE_ASSESSMENTS
            UNION ALL SELECT ''BKMNG_COMPOSITE_PATTERNS'', MAX(CREATED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_COMPOSITE_PATTERNS
            UNION ALL SELECT ''BKMNG_USER_ALERTS'', MAX(CREATED_AT)::VARCHAR, COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_USER_ALERTS
        )
        SELECT
            ch.t AS TABLE_NAME,
            ch.c AS TS_COLUMN,
            a.lr AS LAST_REFRESH,
            a.cnt AS ROW_COUNT,
            ROUND(DATEDIFF(''minute'', TRY_TO_TIMESTAMP_NTZ(a.lr), CURRENT_TIMESTAMP()) / 60.0, 1) AS AGE_HOURS,
            ch.max_h AS MAX_AGE_HOURS,
            CASE
                WHEN a.cnt = 0 THEN ''FAIL''
                WHEN a.lr IS NULL THEN ''FAIL''
                WHEN DATEDIFF(''minute'', TRY_TO_TIMESTAMP_NTZ(a.lr), CURRENT_TIMESTAMP()) / 60.0 > ch.max_h * 2 THEN ''FAIL''
                WHEN DATEDIFF(''minute'', TRY_TO_TIMESTAMP_NTZ(a.lr), CURRENT_TIMESTAMP()) / 60.0 > ch.max_h THEN ''WARN''
                ELSE ''PASS''
            END AS STATUS
        FROM checks ch
        LEFT JOIN actuals a ON a.t = ch.t
        ORDER BY
            CASE WHEN STATUS = ''FAIL'' THEN 1 WHEN STATUS = ''WARN'' THEN 2 ELSE 3 END,
            ch.t
    );
    RETURN TABLE(res);
END;
';
