-- PROCEDURE: TEMP.JUSDAVIS.SP_MANUAL_REFRESH_FOR_ACCOUNT(account_id VARCHAR)
-- Purpose: On-demand refresh of all derived data for a single account.
-- Sources pulled fresh from FIVETRAN.SALESFORCE for: USE_CASES (incl. PS notes)
-- and Gong calls. Then rebuilds ONT row, signals, composite patterns, and
-- appends new alert-eligible signals to BKMNG_USER_ALERTS.
CREATE OR REPLACE PROCEDURE TEMP.JUSDAVIS.SP_MANUAL_REFRESH_FOR_ACCOUNT(ACCOUNT_ID VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    n_uc INT DEFAULT 0;
    n_gong INT DEFAULT 0;
    n_sig INT DEFAULT 0;
    n_alerts INT DEFAULT 0;
BEGIN
    -- 1. MERGE use cases for this account from FIVETRAN (includes fresh PS_NOTES_SUMMARY via CORTEX.SUMMARIZE)
    MERGE INTO TEMP.JUSDAVIS.BKMNG_USE_CASES tgt
    USING (
        SELECT
            uc.ID AS USE_CASE_ID,
            uc.ACCOUNT_C AS ACCOUNT_ID,
            acc.ACCOUNT_NAME,
            COALESCE(uc.NAME_C, uc.NAME) AS USE_CASE_NAME,
            NULL::VARCHAR AS DESCRIPTION,
            uc.USE_CASE_STATUS_C AS STATUS,
            uc.STAGE_C AS STAGE,
            NULL::VARCHAR AS COMPLEXITY,
            uc.ACTUAL_GO_LIVE_DATE_C AS GO_LIVE_DATE,
            NULL::DATE AS TARGET_GO_LIVE_DATE,
            uc.DECISION_DATE_C AS DECISION_DATE,
            lse.EMAIL AS LEAD_SE,
            acc.ACE_ASSIGNED,
            uc.CREATED_DATE,
            CONVERT_TIMEZONE('UTC', uc.LAST_MODIFIED_DATE)::TIMESTAMP_NTZ AS LAST_MODIFIED_DATE,
            LEFT(NULLIF(ARRAY_TO_STRING(ARRAY_COMPACT(ARRAY_CONSTRUCT(
                NULLIF(TRIM(uc.USE_CASE_COMMENTS_C), ''),
                NULLIF(TRIM(uc.IMPLEMENTATION_COMMENTS_C), '')
            )), ' | '), ''), 32768) AS NOTES,
            IFF(
                NULLIF(ARRAY_TO_STRING(ARRAY_COMPACT(ARRAY_CONSTRUCT(
                    NULLIF(TRIM(uc.USE_CASE_COMMENTS_C), ''),
                    NULLIF(TRIM(uc.IMPLEMENTATION_COMMENTS_C), '')
                )), ' | '), '') IS NOT NULL,
                LEFT(SNOWFLAKE.CORTEX.SUMMARIZE(
                    LEFT(NULLIF(ARRAY_TO_STRING(ARRAY_COMPACT(ARRAY_CONSTRUCT(
                        NULLIF(TRIM(uc.USE_CASE_COMMENTS_C), ''),
                        NULLIF(TRIM(uc.IMPLEMENTATION_COMMENTS_C), '')
                    )), ' | '), ''), 8000)
                ), 4000),
                NULL
            ) AS PS_NOTES_SUMMARY,
            uc.OVERALL_SCORE_C AS MEDDPICC_OVERALL_SCORE,
            uc.METRICS_SCORE_C AS MEDDPICC_METRICS_SCORE,
            LEFT(uc.MEDDPICC_METRICS_C, 16384) AS MEDDPICC_METRICS,
            uc.ECONOMIC_BUYER_SCORE_C AS MEDDPICC_ECONOMIC_BUYER_SCORE,
            eb_c.NAME AS MEDDPICC_ECONOMIC_BUYER,
            uc.DECISION_CRITERIA_SCORE_C AS MEDDPICC_DECISION_CRITERIA_SCORE,
            LEFT(uc.MEDDPICC_DECISION_CRITERIA_C, 16384) AS MEDDPICC_DECISION_CRITERIA,
            uc.DECISION_PROCESS_SCORE_C AS MEDDPICC_DECISION_PROCESS_SCORE,
            LEFT(uc.MEDDPICC_DECISION_PROCESS_C, 16384) AS MEDDPICC_DECISION_PROCESS,
            uc.IDENTIFY_PAIN_SCORE_C AS MEDDPICC_IDENTIFY_PAIN_SCORE,
            LEFT(uc.MEDDPICC_IDENTIFY_PAIN_C, 16384) AS MEDDPICC_IDENTIFY_PAIN,
            uc.CHAMPION_SCORE_C AS MEDDPICC_CHAMPION_SCORE,
            champ_c.NAME AS MEDDPICC_CHAMPION,
            uc.COMPETITOR_SCORE_C AS MEDDPICC_COMPETITOR_SCORE,
            uc.COMPETITORS_C AS MEDDPICC_COMPETITORS,
            uc.IMPLEMENTATION_START_DATE_C AS IMPLEMENTATION_START_DATE,
            CURRENT_TIMESTAMP() AS REFRESHED_AT
        FROM FIVETRAN.SALESFORCE.USE_CASE_C uc
        INNER JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS acc
            ON acc.ACCOUNT_ID = uc.ACCOUNT_C
        LEFT JOIN FIVETRAN.SALESFORCE.USER lse
            ON lse.ID = uc.LEAD_SALES_ENGINEER_C
           AND lse._FIVETRAN_DELETED = FALSE
        LEFT JOIN FIVETRAN.SALESFORCE.CONTACT eb_c
            ON eb_c.ID = uc.MEDDPICC_ECONOMIC_BUYER_C
           AND eb_c.IS_DELETED = FALSE
        LEFT JOIN FIVETRAN.SALESFORCE.CONTACT champ_c
            ON champ_c.ID = uc.MEDDPICC_CHAMPION_C
           AND champ_c.IS_DELETED = FALSE
        WHERE uc.IS_DELETED = FALSE
          AND uc.ACCOUNT_C = :ACCOUNT_ID
    ) src
    ON tgt.USE_CASE_ID = src.USE_CASE_ID
    WHEN MATCHED THEN UPDATE SET
        ACCOUNT_ID = src.ACCOUNT_ID,
        ACCOUNT_NAME = src.ACCOUNT_NAME,
        USE_CASE_NAME = src.USE_CASE_NAME,
        STATUS = src.STATUS,
        STAGE = src.STAGE,
        GO_LIVE_DATE = src.GO_LIVE_DATE,
        DECISION_DATE = src.DECISION_DATE,
        LEAD_SE = src.LEAD_SE,
        ACE_ASSIGNED = src.ACE_ASSIGNED,
        CREATED_DATE = src.CREATED_DATE,
        LAST_MODIFIED_DATE = src.LAST_MODIFIED_DATE,
        NOTES = src.NOTES,
        PS_NOTES_SUMMARY = src.PS_NOTES_SUMMARY,
        MEDDPICC_OVERALL_SCORE = src.MEDDPICC_OVERALL_SCORE,
        MEDDPICC_METRICS_SCORE = src.MEDDPICC_METRICS_SCORE,
        MEDDPICC_METRICS = src.MEDDPICC_METRICS,
        MEDDPICC_ECONOMIC_BUYER_SCORE = src.MEDDPICC_ECONOMIC_BUYER_SCORE,
        MEDDPICC_ECONOMIC_BUYER = src.MEDDPICC_ECONOMIC_BUYER,
        MEDDPICC_DECISION_CRITERIA_SCORE = src.MEDDPICC_DECISION_CRITERIA_SCORE,
        MEDDPICC_DECISION_CRITERIA = src.MEDDPICC_DECISION_CRITERIA,
        MEDDPICC_DECISION_PROCESS_SCORE = src.MEDDPICC_DECISION_PROCESS_SCORE,
        MEDDPICC_DECISION_PROCESS = src.MEDDPICC_DECISION_PROCESS,
        MEDDPICC_IDENTIFY_PAIN_SCORE = src.MEDDPICC_IDENTIFY_PAIN_SCORE,
        MEDDPICC_IDENTIFY_PAIN = src.MEDDPICC_IDENTIFY_PAIN,
        MEDDPICC_CHAMPION_SCORE = src.MEDDPICC_CHAMPION_SCORE,
        MEDDPICC_CHAMPION = src.MEDDPICC_CHAMPION,
        MEDDPICC_COMPETITOR_SCORE = src.MEDDPICC_COMPETITOR_SCORE,
        MEDDPICC_COMPETITORS = src.MEDDPICC_COMPETITORS,
        IMPLEMENTATION_START_DATE = src.IMPLEMENTATION_START_DATE,
        REFRESHED_AT = src.REFRESHED_AT
    WHEN NOT MATCHED THEN INSERT (
        USE_CASE_ID, ACCOUNT_ID, ACCOUNT_NAME, USE_CASE_NAME, DESCRIPTION,
        STATUS, STAGE, COMPLEXITY, GO_LIVE_DATE, TARGET_GO_LIVE_DATE,
        DECISION_DATE, LEAD_SE, ACE_ASSIGNED, CREATED_DATE, LAST_MODIFIED_DATE,
        NOTES, PS_NOTES_SUMMARY,
        MEDDPICC_OVERALL_SCORE, MEDDPICC_METRICS_SCORE, MEDDPICC_METRICS,
        MEDDPICC_ECONOMIC_BUYER_SCORE, MEDDPICC_ECONOMIC_BUYER,
        MEDDPICC_DECISION_CRITERIA_SCORE, MEDDPICC_DECISION_CRITERIA,
        MEDDPICC_DECISION_PROCESS_SCORE, MEDDPICC_DECISION_PROCESS,
        MEDDPICC_IDENTIFY_PAIN_SCORE, MEDDPICC_IDENTIFY_PAIN,
        MEDDPICC_CHAMPION_SCORE, MEDDPICC_CHAMPION,
        MEDDPICC_COMPETITOR_SCORE, MEDDPICC_COMPETITORS,
        IMPLEMENTATION_START_DATE, REFRESHED_AT
    )
    VALUES (
        src.USE_CASE_ID, src.ACCOUNT_ID, src.ACCOUNT_NAME, src.USE_CASE_NAME, src.DESCRIPTION,
        src.STATUS, src.STAGE, src.COMPLEXITY, src.GO_LIVE_DATE, src.TARGET_GO_LIVE_DATE,
        src.DECISION_DATE, src.LEAD_SE, src.ACE_ASSIGNED, src.CREATED_DATE, src.LAST_MODIFIED_DATE,
        src.NOTES, src.PS_NOTES_SUMMARY,
        src.MEDDPICC_OVERALL_SCORE, src.MEDDPICC_METRICS_SCORE, src.MEDDPICC_METRICS,
        src.MEDDPICC_ECONOMIC_BUYER_SCORE, src.MEDDPICC_ECONOMIC_BUYER,
        src.MEDDPICC_DECISION_CRITERIA_SCORE, src.MEDDPICC_DECISION_CRITERIA,
        src.MEDDPICC_DECISION_PROCESS_SCORE, src.MEDDPICC_DECISION_PROCESS,
        src.MEDDPICC_IDENTIFY_PAIN_SCORE, src.MEDDPICC_IDENTIFY_PAIN,
        src.MEDDPICC_CHAMPION_SCORE, src.MEDDPICC_CHAMPION,
        src.MEDDPICC_COMPETITOR_SCORE, src.MEDDPICC_COMPETITORS,
        src.IMPLEMENTATION_START_DATE, src.REFRESHED_AT
    );
    SELECT COUNT(*) INTO :n_uc FROM TEMP.JUSDAVIS.BKMNG_USE_CASES WHERE ACCOUNT_ID = :ACCOUNT_ID;

    -- 2. Parse any newly-changed PS notes. Wrap in exception handler because this SP
    --    processes ALL accounts' changed notes and can fail on unrelated Cortex errors.
    --    The scheduled task will retry; we don't want to fail a per-account refresh.
    BEGIN
        CALL TEMP.JUSDAVIS.SP_PARSE_BKMNG_USE_CASE_NOTES();
    EXCEPTION
        WHEN OTHER THEN
            NULL;
    END;

    -- 3. MERGE Gong calls for this account from FIVETRAN (90d lookback)
    MERGE INTO TEMP.JUSDAVIS.BKMNG_GONG_CALLS tgt
    USING (
        SELECT
            g.ID AS CALL_ID,
            g.GONG_PRIMARY_ACCOUNT_C AS ACCOUNT_ID,
            a.ACCOUNT_NAME,
            g.GONG_TITLE_C AS TITLE,
            g.GONG_CALL_START_C::TIMESTAMP_NTZ AS CALL_DATE,
            FLOOR(g.GONG_CALL_DURATION_SEC_C / 60) AS DURATION_MINS,
            LEFT(g.GONG_RELATED_TOPICS_JSON_C, 4000) AS TOPICS,
            LEFT(g.GONG_CALL_HIGHLIGHTS_NEXT_STEPS_C, 4000) AS NEXT_STEPS,
            g.GONG_VIEW_CALL_C AS RECORDING_URL,
            LEFT(g.GONG_PARTICIPANTS_EMAILS_C, 2000) AS PARTICIPANTS,
            LEFT(g.GONG_CALL_BRIEF_C, 4000) AS SUMMARY,
            LEFT(g.GONG_CALL_KEY_POINTS_C, 4000) AS KEY_POINTS,
            CURRENT_TIMESTAMP() AS REFRESHED_AT
        FROM FIVETRAN.SALESFORCE.GONG_GONG_CALL_C g
        JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS a ON a.ACCOUNT_ID = g.GONG_PRIMARY_ACCOUNT_C
        WHERE g.GONG_CALL_START_C >= DATEADD('day', -90, CURRENT_TIMESTAMP())
          AND g.GONG_PRIMARY_ACCOUNT_C = :ACCOUNT_ID
    ) src
    ON tgt.CALL_ID = src.CALL_ID
    WHEN MATCHED THEN UPDATE SET
        ACCOUNT_ID = src.ACCOUNT_ID, ACCOUNT_NAME = src.ACCOUNT_NAME,
        TITLE = src.TITLE, CALL_DATE = src.CALL_DATE, DURATION_MINS = src.DURATION_MINS,
        TOPICS = src.TOPICS, NEXT_STEPS = src.NEXT_STEPS, RECORDING_URL = src.RECORDING_URL,
        PARTICIPANTS = src.PARTICIPANTS, SUMMARY = src.SUMMARY, KEY_POINTS = src.KEY_POINTS,
        REFRESHED_AT = src.REFRESHED_AT
    WHEN NOT MATCHED THEN INSERT (
        CALL_ID, ACCOUNT_ID, ACCOUNT_NAME, TITLE, CALL_DATE, DURATION_MINS,
        TOPICS, NEXT_STEPS, RECORDING_URL, PARTICIPANTS, SUMMARY, KEY_POINTS, REFRESHED_AT
    ) VALUES (
        src.CALL_ID, src.ACCOUNT_ID, src.ACCOUNT_NAME, src.TITLE, src.CALL_DATE, src.DURATION_MINS,
        src.TOPICS, src.NEXT_STEPS, src.RECORDING_URL, src.PARTICIPANTS, src.SUMMARY, src.KEY_POINTS, src.REFRESHED_AT
    );
    SELECT COUNT(*) INTO :n_gong FROM TEMP.JUSDAVIS.BKMNG_GONG_CALLS WHERE ACCOUNT_ID = :ACCOUNT_ID;

    -- 4. Refresh ONT_INTERACTIONS for this account (DELETE + INSERT scoped)
    DELETE FROM TEMP.JUSDAVIS.BKMNG_ONT_INTERACTIONS WHERE ACCOUNT_ID = :ACCOUNT_ID;
    INSERT INTO TEMP.JUSDAVIS.BKMNG_ONT_INTERACTIONS
    WITH scoped_calls AS (
        SELECT g.ID, g.GONG_PRIMARY_ACCOUNT_C, a.ACCOUNT_NAME,
               g.GONG_CALL_START_C, g.GONG_TITLE_C,
               g.GONG_CALL_BRIEF_C, g.GONG_CALL_KEY_POINTS_C, g.GONG_CALL_HIGHLIGHTS_NEXT_STEPS_C,
               g.GONG_RELATED_TOPICS_JSON_C, g.GONG_RELATED_TRACKERS_JSON_C,
               g.GONG_PARTICIPANTS_EMAILS_C,
               g.GONG_CALL_DURATION_SEC_C, g.GONG_TALK_TIME_US_C, g.GONG_TALK_TIME_THEM_C,
               g.GONG_CALL_SCORE_C, g.GONG_VIEW_CALL_C
        FROM FIVETRAN.SALESFORCE.GONG_GONG_CALL_C g
        INNER JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS a ON a.ACCOUNT_ID = g.GONG_PRIMARY_ACCOUNT_C
        WHERE g.IS_DELETED = FALSE
          AND g.GONG_PRIMARY_ACCOUNT_C = :ACCOUNT_ID
    ),
    topics_agg AS (
        SELECT s.ID AS CALL_ID,
               NULLIF(ARRAY_TO_STRING(ARRAY_AGG(DISTINCT CASE WHEN t.VALUE IS NOT NULL THEN t.value:Name::STRING END), ', '), '') AS TOPICS
        FROM scoped_calls s
        LEFT JOIN LATERAL FLATTEN(input => TRY_PARSE_JSON(s.GONG_RELATED_TOPICS_JSON_C), OUTER => TRUE) t
        GROUP BY s.ID
    ),
    trackers_agg AS (
        SELECT s.ID AS CALL_ID,
               NULLIF(ARRAY_TO_STRING(ARRAY_AGG(DISTINCT CASE WHEN tr.VALUE IS NOT NULL THEN tr.value:Name::STRING END), ', '), '') AS TRACKERS
        FROM scoped_calls s
        LEFT JOIN LATERAL FLATTEN(input => TRY_PARSE_JSON(s.GONG_RELATED_TRACKERS_JSON_C), OUTER => TRUE) tr
        GROUP BY s.ID
    )
    SELECT c.ID, c.GONG_PRIMARY_ACCOUNT_C, c.ACCOUNT_NAME, 'gong_call',
           c.GONG_CALL_START_C, c.GONG_TITLE_C,
           LEFT(REGEXP_REPLACE(COALESCE(c.GONG_CALL_BRIEF_C,''), '<[^>]+>', ''), 8000),
           LEFT(REGEXP_REPLACE(COALESCE(c.GONG_CALL_KEY_POINTS_C,''), '<[^>]+>', ''), 4000),
           LEFT(REGEXP_REPLACE(COALESCE(c.GONG_CALL_HIGHLIGHTS_NEXT_STEPS_C,''), '<[^>]+>', ''), 4000),
           ta.TOPICS, tr.TRACKERS, c.GONG_PARTICIPANTS_EMAILS_C,
           c.GONG_CALL_DURATION_SEC_C, c.GONG_TALK_TIME_US_C, c.GONG_TALK_TIME_THEM_C,
           c.GONG_CALL_SCORE_C, c.GONG_VIEW_CALL_C, CURRENT_TIMESTAMP()
    FROM scoped_calls c
    LEFT JOIN topics_agg ta ON ta.CALL_ID = c.ID
    LEFT JOIN trackers_agg tr ON tr.CALL_ID = c.ID;

    -- 5. Refresh ONT_ACCOUNTS row for this account (DELETE + INSERT)
    DELETE FROM TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNTS WHERE ACCOUNT_ID = :ACCOUNT_ID;
    INSERT INTO TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNTS
    WITH contract_cte AS (
        SELECT
            ACCOUNT_ID,
            NET_TCV AS CONTRACT_CAPACITY,
            REV_180D AS TOTAL_CONSUMED_CREDITS,
            GREATEST(0, COALESCE(NET_TCV, 0) - COALESCE(REV_180D, 0)) AS CAPACITY_REMAINING,
            PREDICTED_OVERAGE_DATE,
            CASE WHEN NET_ACV > 0 THEN ROUND(REV_90D * (365.0/90) / NET_ACV * 100, 1) ELSE NULL END AS CONTRACT_UTILIZATION_PCT
        FROM TEMP.JUSDAVIS.BKMNG_A360_CONTRACT
        WHERE ACCOUNT_ID = :ACCOUNT_ID
    ),
    consumption_cte AS (
        SELECT ACCOUNT_ID, WOW_PCT_CHANGE, MOM_PCT_CHANGE
        FROM TEMP.JUSDAVIS.BKMNG_A360_CONSUMPTION
        WHERE ACCOUNT_ID = :ACCOUNT_ID
    ),
    interaction_agg AS (
        SELECT ACCOUNT_ID,
               COUNT(CASE WHEN INTERACTION_DATE >= DATEADD('day',-90,CURRENT_TIMESTAMP()) THEN 1 END) AS TOTAL_GONG_CALLS_90D,
               AVG(CASE WHEN INTERACTION_DATE >= DATEADD('day',-90,CURRENT_TIMESTAMP()) THEN CALL_SCORE END) AS AVG_GONG_SCORE_90D,
               MAX(INTERACTION_DATE::DATE) AS LAST_EXTERNAL_INTERACTION_DATE
        FROM TEMP.JUSDAVIS.BKMNG_ONT_INTERACTIONS
        WHERE ACCOUNT_ID = :ACCOUNT_ID
        GROUP BY ACCOUNT_ID
    ),
    uc_agg AS (
        SELECT ACCOUNT_ID,
               COUNT(CASE WHEN STATUS IN ('In Pursuit','Implementation') THEN 1 END) AS ACTIVE_USE_CASE_COUNT,
               COUNT(CASE WHEN STATUS = 'Implementation' THEN 1 END) AS IMPL_USE_CASE_COUNT,
               COUNT(CASE WHEN STATUS = 'Blocked' THEN 1 END) AS BLOCKED_USE_CASE_COUNT,
               AVG(MEDDPICC_OVERALL_SCORE) AS AVG_MEDDPICC_SCORE
        FROM TEMP.JUSDAVIS.BKMNG_USE_CASES
        WHERE ACCOUNT_ID = :ACCOUNT_ID
        GROUP BY ACCOUNT_ID
    ),
    base AS (
        SELECT a.*, cr.CONTRACT_UTILIZATION_PCT, cr.TOTAL_CONSUMED_CREDITS, cr.CONTRACT_CAPACITY,
               cr.CAPACITY_REMAINING, cr.PREDICTED_OVERAGE_DATE, cn.WOW_PCT_CHANGE, cn.MOM_PCT_CHANGE,
               ia.TOTAL_GONG_CALLS_90D, ia.AVG_GONG_SCORE_90D, ia.LAST_EXTERNAL_INTERACTION_DATE,
               DATEDIFF('day', ia.LAST_EXTERNAL_INTERACTION_DATE, CURRENT_DATE()) AS DAYS_SINCE_LAST_INTERACTION,
               ua.ACTIVE_USE_CASE_COUNT, ua.IMPL_USE_CASE_COUNT, ua.BLOCKED_USE_CASE_COUNT, ua.AVG_MEDDPICC_SCORE
        FROM (
            SELECT a0.* REPLACE (
                COALESCE(s.STATUS, a0.STATUS, 'active') AS STATUS,
                COALESCE(s.ENGAGEMENT_STATUS, a0.ENGAGEMENT_STATUS, 'Normal') AS ENGAGEMENT_STATUS
            )
            FROM TEMP.JUSDAVIS.BKMNG_ACCOUNTS a0
            LEFT JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNT_SETTINGS s ON s.ACCOUNT_ID = a0.ACCOUNT_ID
        ) a
        LEFT JOIN contract_cte cr ON cr.ACCOUNT_ID = a.ACCOUNT_ID
        LEFT JOIN consumption_cte cn ON cn.ACCOUNT_ID = a.ACCOUNT_ID
        LEFT JOIN interaction_agg ia ON ia.ACCOUNT_ID = a.ACCOUNT_ID
        LEFT JOIN uc_agg ua ON ua.ACCOUNT_ID = a.ACCOUNT_ID
        WHERE a.ACCOUNT_ID = :ACCOUNT_ID
    ),
    health_scored AS (
        SELECT *,
            ROUND((
                LEAST(100, GREATEST(0, 50 + COALESCE(WOW_PCT_CHANGE,0)))        * 0.25 +
                LEAST(100, GREATEST(0, COALESCE(IMPL_USE_CASE_COUNT,0) * 25))   * 0.25 +
                CASE WHEN LAST_EXTERNAL_INTERACTION_DATE IS NULL THEN 0
                     WHEN DAYS_SINCE_LAST_INTERACTION < 7 THEN 100
                     WHEN DAYS_SINCE_LAST_INTERACTION < 14 THEN 75
                     WHEN DAYS_SINCE_LAST_INTERACTION < 30 THEN 40
                     ELSE 10 END                                                 * 0.25 +
                LEAST(100, GREATEST(0, COALESCE(AVG_MEDDPICC_SCORE,50)))        * 0.25
            ), 1) AS HEALTH_SCORE
        FROM base
    ),
    new_adoption_30d_cte AS (
        SELECT ACCOUNT_ID,
               LISTAGG(FEATURE, ', ') WITHIN GROUP (ORDER BY FEATURE) AS NEW_ADOPTION_30D
        FROM TEMP.JUSDAVIS.BKMNG_A360_PRODUCT_ADOPTION
        WHERE IS_NEW_30D = TRUE AND ACCOUNT_ID = :ACCOUNT_ID
        GROUP BY ACCOUNT_ID
    ),
    adoption_signals_cte AS (
        SELECT
            ACCOUNT_ID,
            MAX(CASE WHEN PRODUCT_CATEGORY = 'Data Engineering' AND USE_CASE = 'Ingestion'       AND IS_ACTIVE_30D THEN 1 ELSE 0 END) AS SIG_PIPELINE,
            MAX(CASE WHEN PRODUCT_CATEGORY = 'Data Engineering' AND USE_CASE = 'Transformation'  AND IS_ACTIVE_30D THEN 1 ELSE 0 END) AS SIG_TRANSFORMS,
            MAX(CASE WHEN PRODUCT_CATEGORY = 'Analytics'                                         AND IS_ACTIVE_30D THEN 1 ELSE 0 END) AS SIG_BI,
            MAX(CASE WHEN PRODUCT_CATEGORY = 'Platform'         AND USE_CASE = 'Cost Governance' AND IS_ACTIVE_30D THEN 1 ELSE 0 END) AS SIG_COST,
            MAX(CASE WHEN PRODUCT_CATEGORY = 'Applications & Collaboration'                      AND IS_ACTIVE_30D THEN 1 ELSE 0 END) AS SIG_COLLAB,
            MAX(CASE WHEN PRODUCT_CATEGORY = 'Platform'         AND USE_CASE = 'Observability'   AND IS_ACTIVE_30D THEN 1 ELSE 0 END) AS SIG_OBS,
            MAX(CASE WHEN PRODUCT_CATEGORY = 'AI/ML'                                             AND IS_ACTIVE_30D THEN 1 ELSE 0 END) AS SIG_AIML,
            MAX(CASE WHEN PRODUCT_CATEGORY = 'Transactions'                                      AND IS_ACTIVE_30D THEN 1 ELSE 0 END) AS SIG_SPCS
        FROM TEMP.JUSDAVIS.BKMNG_A360_PRODUCT_ADOPTION
        WHERE ACCOUNT_ID = :ACCOUNT_ID
        GROUP BY ACCOUNT_ID
    ),
    meeting_agg AS (
        SELECT ACCOUNT_ID,
               COUNT(CASE WHEN IS_UPCOMING = FALSE AND ACTIVITY_DATE >= DATEADD('day', -30, CURRENT_DATE()) THEN 1 END) AS MEETINGS_LAST_30D,
               COUNT(CASE WHEN IS_UPCOMING = TRUE  AND ACTIVITY_DATE <= DATEADD('day',  5, CURRENT_DATE()) THEN 1 END) AS UPCOMING_MEETINGS_5D,
               MAX(CASE WHEN IS_UPCOMING = FALSE THEN ACTIVITY_DATE END) AS LAST_MEETING_DATE
        FROM TEMP.JUSDAVIS.BKMNG_MEETING_ACTIVITY
        WHERE ACCOUNT_ID = :ACCOUNT_ID
        GROUP BY ACCOUNT_ID
    ),
    adoption_profile_cte AS (
        SELECT ACCOUNT_ID, ADOPTION_PROFILE, MISSING_CATEGORIES
        FROM TEMP.JUSDAVIS.BKMNG_ADOPTION_SIGNALS
        WHERE ACCOUNT_ID = :ACCOUNT_ID
    ),
    champion_cte AS (
        SELECT ACCOUNT_ID,
               COUNT(*)                  AS CHAMPION_COUNT,
               MAX(LAST_GONG_CALL_DATE)  AS CHAMPION_LAST_GONG_DATE,
               MIN(DAYS_SINCE_LAST_CALL) AS CHAMPION_DAYS_SINCE_CALL
        FROM TEMP.JUSDAVIS.BKMNG_ONT_CONTACTS
        WHERE IS_CHAMPION = TRUE AND ACCOUNT_ID = :ACCOUNT_ID
        GROUP BY ACCOUNT_ID
    ),
    ai_cte AS (
        SELECT ACCOUNT_ID, AI_PRIORITY_SCORE, PRIORITY_TIER AS AI_PRIORITY_TIER
        FROM TEMP.JUSDAVIS.BKMNG_AI_ACCOUNT_ASSESSMENTS
        WHERE ACCOUNT_ID = :ACCOUNT_ID
    ),
    security_cte AS (
        SELECT ACCOUNT_ID,
               ROUND(
                   SUM(CASE WHEN STATUS = 'green' THEN 1 ELSE 0 END) /
                   NULLIF(COUNT(*) - SUM(CASE WHEN STATUS = 'not_applicable' THEN 1 ELSE 0 END), 0) * 100
               )                             AS SECURITY_SCORE_PCT,
               SUM(CASE WHEN STATUS = 'red' THEN 1 ELSE 0 END) AS SECURITY_RED_COUNT
        FROM TEMP.JUSDAVIS.BKMNG_SECURITY_POSTURE
        WHERE ACCOUNT_ID = :ACCOUNT_ID
        GROUP BY ACCOUNT_ID
    ),
    topics_cte AS (
        SELECT ACCOUNT_ID,
               LISTAGG(TOPIC, ', ') WITHIN GROUP (ORDER BY MENTION_COUNT_90D DESC) AS TOP_TOPICS
        FROM (
            SELECT ACCOUNT_ID, TOPIC, MENTION_COUNT_90D,
                   ROW_NUMBER() OVER (PARTITION BY ACCOUNT_ID ORDER BY MENTION_COUNT_90D DESC) AS rn
            FROM TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNT_TOPICS
            WHERE ACCOUNT_ID = :ACCOUNT_ID
        )
        WHERE rn <= 5
        GROUP BY ACCOUNT_ID
    ),
    competitors_cte AS (
        SELECT ACCOUNT_ID,
               LISTAGG(COMPETITOR_NAME, ', ') WITHIN GROUP (ORDER BY MENTION_COUNT_90D DESC) AS TOP_COMPETITORS,
               SUM(MENTION_COUNT_90D) AS COMPETITOR_MENTIONS_90D
        FROM (
            SELECT ACCOUNT_ID, COMPETITOR_NAME, MENTION_COUNT_90D,
                   ROW_NUMBER() OVER (PARTITION BY ACCOUNT_ID ORDER BY MENTION_COUNT_90D DESC) AS rn
            FROM TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNT_COMPETITORS
            WHERE ACCOUNT_ID = :ACCOUNT_ID
        )
        WHERE rn <= 3
        GROUP BY ACCOUNT_ID
    ),
    opp_cte AS (
        SELECT ACCOUNT_ID,
               COUNT(*)        AS OPEN_OPP_COUNT,
               MIN(CLOSE_DATE) AS NEXT_OPP_CLOSE_DATE,
               SUM(AMOUNT)     AS TOTAL_OPP_AMOUNT
        FROM TEMP.JUSDAVIS.BKMNG_ONT_OPPORTUNITIES
        WHERE ACCOUNT_ID = :ACCOUNT_ID
          AND STAGE NOT IN ('Closed Won', 'Closed Lost', 'ClosedWon', 'Duplicate')
        GROUP BY ACCOUNT_ID
    ),
    support_cte AS (
        SELECT ACCOUNT_ID,
               SUM(CASE WHEN IS_CLOSED = FALSE THEN 1 ELSE 0 END)                                     AS OPEN_TICKET_COUNT,
               SUM(CASE WHEN IS_CLOSED = FALSE AND SEVERITY LIKE 'Severity-1%' THEN 1 ELSE 0 END)     AS OPEN_SEV1_COUNT
        FROM TEMP.JUSDAVIS.BKMNG_SUPPORT_TICKETS
        WHERE ACCOUNT_ID = :ACCOUNT_ID
        GROUP BY ACCOUNT_ID
    )
    SELECT
        hs.ACCOUNT_ID, hs.ACCOUNT_NAME, hs.INDUSTRY, hs.REGION, hs.ACE_USER_ID, hs.ACE_ASSIGNED,
        hs.ENGAGEMENT_STATUS, hs.STATUS, hs.ACTIVATION_START_DATE, hs.TOTAL_CREDITS_ALLOCATED,
        hs.ACV, hs.CONSUMPTION_YTD, hs.REFRESHED_AT, hs.LEAD_SE_EMAIL, hs.AE_EMAIL,
        hs.CONTRACT_UTILIZATION_PCT, hs.TOTAL_CONSUMED_CREDITS, hs.CONTRACT_CAPACITY,
        hs.CAPACITY_REMAINING, hs.PREDICTED_OVERAGE_DATE, hs.WOW_PCT_CHANGE, hs.MOM_PCT_CHANGE,
        hs.TOTAL_GONG_CALLS_90D, hs.AVG_GONG_SCORE_90D, hs.LAST_EXTERNAL_INTERACTION_DATE,
        hs.DAYS_SINCE_LAST_INTERACTION, hs.ACTIVE_USE_CASE_COUNT, hs.IMPL_USE_CASE_COUNT,
        hs.BLOCKED_USE_CASE_COUNT, hs.AVG_MEDDPICC_SCORE, hs.HEALTH_SCORE,
        CASE WHEN hs.HEALTH_SCORE>=70 THEN 'accelerating'
             WHEN hs.HEALTH_SCORE>=45 THEN 'steady'
             WHEN hs.HEALTH_SCORE>=25 THEN 'decelerating'
             ELSE 'stalled' END AS MOMENTUM,
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS ONT_REFRESHED_AT,
        COALESCE(ads.SIG_PIPELINE, 0), COALESCE(ads.SIG_TRANSFORMS, 0), COALESCE(ads.SIG_BI, 0),
        COALESCE(ads.SIG_COST, 0), COALESCE(ads.SIG_COLLAB, 0), COALESCE(ads.SIG_OBS, 0),
        COALESCE(ads.SIG_AIML, 0), COALESCE(ads.SIG_SPCS, 0),
        COALESCE(ads.SIG_PIPELINE, 0) + COALESCE(ads.SIG_TRANSFORMS, 0) + COALESCE(ads.SIG_BI, 0)
            + COALESCE(ads.SIG_COST, 0) + COALESCE(ads.SIG_COLLAB, 0) + COALESCE(ads.SIG_OBS, 0)
            + COALESCE(ads.SIG_AIML, 0) + COALESCE(ads.SIG_SPCS, 0) AS ADOPTION_SIGNAL_COUNT,
        ap.ADOPTION_PROFILE,
        ap.MISSING_CATEGORIES,
        na.NEW_ADOPTION_30D,
        COALESCE(ma.MEETINGS_LAST_30D, 0), COALESCE(ma.UPCOMING_MEETINGS_5D, 0), ma.LAST_MEETING_DATE,
        COALESCE(ea.EMAILS_LAST_30D, 0), ea.LAST_EMAIL_DATE, ea.EMAIL_TREND,
        hs.AE_NAME,
        COALESCE(ch.CHAMPION_COUNT, 0),
        ch.CHAMPION_LAST_GONG_DATE,
        ch.CHAMPION_DAYS_SINCE_CALL,
        ai.AI_PRIORITY_SCORE,
        ai.AI_PRIORITY_TIER,
        sc.SECURITY_SCORE_PCT,
        COALESCE(sc.SECURITY_RED_COUNT, 0),
        tp.TOP_TOPICS,
        cm.TOP_COMPETITORS,
        COALESCE(cm.COMPETITOR_MENTIONS_90D, 0),
        COALESCE(op.OPEN_OPP_COUNT, 0),
        op.NEXT_OPP_CLOSE_DATE,
        op.TOTAL_OPP_AMOUNT,
        COALESCE(su.OPEN_TICKET_COUNT, 0),
        COALESCE(su.OPEN_SEV1_COUNT, 0),
        s2.PRIMARY_ACE_EMAIL,
        s2.COVERAGE_ACE_EMAIL,
        s2.COVERAGE_UNTIL
    FROM health_scored hs
    LEFT JOIN adoption_signals_cte ads ON ads.ACCOUNT_ID = hs.ACCOUNT_ID
    LEFT JOIN adoption_profile_cte  ap  ON ap.ACCOUNT_ID  = hs.ACCOUNT_ID
    LEFT JOIN new_adoption_30d_cte  na  ON na.ACCOUNT_ID  = hs.ACCOUNT_ID
    LEFT JOIN meeting_agg           ma  ON ma.ACCOUNT_ID  = hs.ACCOUNT_ID
    LEFT JOIN TEMP.JUSDAVIS.BKMNG_EMAIL_ACTIVITY ea ON ea.ACCOUNT_ID = hs.ACCOUNT_ID
    LEFT JOIN champion_cte          ch  ON ch.ACCOUNT_ID  = hs.ACCOUNT_ID
    LEFT JOIN ai_cte                ai  ON ai.ACCOUNT_ID  = hs.ACCOUNT_ID
    LEFT JOIN security_cte          sc  ON sc.ACCOUNT_ID  = hs.ACCOUNT_ID
    LEFT JOIN topics_cte            tp  ON tp.ACCOUNT_ID  = hs.ACCOUNT_ID
    LEFT JOIN competitors_cte       cm  ON cm.ACCOUNT_ID  = hs.ACCOUNT_ID
    LEFT JOIN opp_cte               op  ON op.ACCOUNT_ID  = hs.ACCOUNT_ID
    LEFT JOIN support_cte           su  ON su.ACCOUNT_ID  = hs.ACCOUNT_ID
    LEFT JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNT_SETTINGS s2 ON s2.ACCOUNT_ID = hs.ACCOUNT_ID;

    -- 6. Refresh core signals for this account (DELETE + INSERT scoped). Calls full SP then
    --    restores other accounts' core signals is not feasible; instead we re-run all the
    --    insert blocks scoped by account_id.
    DELETE FROM TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNT_SIGNALS
     WHERE ACCOUNT_ID = :ACCOUNT_ID AND (SOURCE = 'core' OR SOURCE IS NULL);

    -- Re-run the full core signals SP (it DELETEs all 'core' and re-inserts) OR do scoped.
    -- To keep this fast and isolated, we call the full SP which rebuilds all core signals.
    CALL TEMP.JUSDAVIS.SP_REFRESH_BKMNG_ONT_ACCOUNT_SIGNALS();

    SELECT COUNT(*) INTO :n_sig FROM TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNT_SIGNALS WHERE ACCOUNT_ID = :ACCOUNT_ID;

    -- 7. Refresh composite patterns for this account
    DELETE FROM TEMP.JUSDAVIS.BKMNG_COMPOSITE_PATTERNS WHERE ACCOUNT_ID = :ACCOUNT_ID;
    -- Composite patterns SP does TRUNCATE+INSERT over all accounts; safer to call the full SP.
    CALL TEMP.JUSDAVIS.SP_COMPUTE_COMPOSITE_PATTERNS();

    -- 8. Append new alert-eligible signals for this account to BKMNG_USER_ALERTS
    INSERT INTO TEMP.JUSDAVIS.BKMNG_USER_ALERTS
        (USER_EMAIL, SIGNAL_ID, SIGNAL_TYPE, ACCOUNT_ID, ACCOUNT_NAME, TEXT, PRIORITY, SOURCE)
    SELECT DISTINCT
        a.ACE_ASSIGNED, s.SIGNAL_ID, s.SIGNAL_TYPE, s.ACCOUNT_ID, s.ACCOUNT_NAME,
        s.SIGNAL_TEXT, COALESCE(p.PRIORITY_OVERRIDE, s.PRIORITY), s.SOURCE
    FROM TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNT_SIGNALS s
    JOIN TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNTS a ON a.ACCOUNT_ID = s.ACCOUNT_ID
    LEFT JOIN TEMP.JUSDAVIS.BKMNG_USER_ALERT_PREFERENCES p
      ON p.USER_EMAIL = a.ACE_ASSIGNED AND p.SIGNAL_TYPE = s.SIGNAL_TYPE
    WHERE s.ACCOUNT_ID = :ACCOUNT_ID
      AND s.ALERT_ELIGIBLE = TRUE
      AND a.ACE_ASSIGNED IS NOT NULL
      AND (p.ENABLED IS NULL OR p.ENABLED = TRUE)
      AND NOT EXISTS (
          SELECT 1 FROM TEMP.JUSDAVIS.BKMNG_USER_ALERTS ua
          WHERE ua.SIGNAL_ID = s.SIGNAL_ID AND ua.USER_EMAIL = a.ACE_ASSIGNED
      );
    SELECT COUNT(*) INTO :n_alerts FROM TEMP.JUSDAVIS.BKMNG_USER_ALERTS
      WHERE ACCOUNT_ID = :ACCOUNT_ID AND IS_DISMISSED = FALSE;

    RETURN 'OK: account=' || :ACCOUNT_ID
        || ' use_cases=' || :n_uc::VARCHAR
        || ' gong_calls=' || :n_gong::VARCHAR
        || ' signals=' || :n_sig::VARCHAR
        || ' active_alerts=' || :n_alerts::VARCHAR;
END;
$$;
