-- PROCEDURE: TEMP.JUSDAVIS.SP_REFRESH_BKMNG_CONTRACT_REVENUE()  |  created: 2026-04-04 02:25:40.843000+00:00

CREATE OR REPLACE PROCEDURE "SP_REFRESH_BKMNG_CONTRACT_REVENUE"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    TRUNCATE TABLE TEMP.JUSDAVIS.BKMNG_CONTRACT_REVENUE;
    INSERT INTO TEMP.JUSDAVIS.BKMNG_CONTRACT_REVENUE (
        ACCOUNT_ID, ACCOUNT_NAME, CONTRACT_START_DATE, CONTRACT_END_DATE,
        CONTRACT_CAPACITY, TOTAL_CONSUMED_REVENUE, CAPACITY_REMAINING,
        TOTAL_CONSUMED_CREDITS, PREDICTED_OVERAGE_DATE, LAST_ACTUAL_DATE, REFRESHED_AT
    )
    SELECT
        r.SALESFORCE_ACCOUNT_ID,
        r.SALESFORCE_ACCOUNT_NAME,
        r.CONTRACT_START_DATE,
        r.CONTRACT_END_DATE,
        r.CONTRACT_CAPACITY,
        r.TOTAL_CONSUMED_REVENUE,
        r.CONTRACT_CAPACITY - r.TOTAL_CONSUMED_REVENUE,
        r.TOTAL_CONSUMED_CREDITS,
        r.PREDICTED_OVERAGE_DATE,
        r.LAST_ACTUAL_DATE,
        CURRENT_TIMESTAMP()
    FROM (
        SELECT
            SALESFORCE_ACCOUNT_ID,
            MAX(SALESFORCE_ACCOUNT_NAME)                                    AS SALESFORCE_ACCOUNT_NAME,
            MIN(GENERAL_DATE)                                               AS CONTRACT_START_DATE,
            MAX(GENERAL_DATE)                                               AS CONTRACT_END_DATE,
            MAX(CAPACITY_CONTRACT_AMOUNT_STRAIGHT_LINE)                     AS CONTRACT_CAPACITY,
            SUM(CASE WHEN IS_FUTURE = FALSE THEN REVENUE       ELSE 0 END) AS TOTAL_CONSUMED_REVENUE,
            SUM(CASE WHEN IS_FUTURE = FALSE THEN TOTAL_CREDITS ELSE 0 END) AS TOTAL_CONSUMED_CREDITS,
            MAX(DAY_OF_OVERAGE)                                             AS PREDICTED_OVERAGE_DATE,
            MAX(CASE WHEN IS_FUTURE = FALSE THEN GENERAL_DATE END)          AS LAST_ACTUAL_DATE
        FROM SALES.REPORTING.FACT_CONTRACT_REVENUE_DAILY
        GROUP BY SALESFORCE_ACCOUNT_ID
    ) r
    INNER JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS a ON a.ACCOUNT_ID = r.SALESFORCE_ACCOUNT_ID;
    RETURN ''OK'';
END;
';
