-- PROCEDURE: TEMP.JUSDAVIS.SP_REFRESH_BKMNG_A360_PRODUCT_ADOPTION()  |  created: 2026-04-21 00:57:05.734000+00:00

CREATE OR REPLACE PROCEDURE "SP_REFRESH_BKMNG_A360_PRODUCT_ADOPTION"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    CREATE OR REPLACE TABLE TEMP.JUSDAVIS.BKMNG_A360_PRODUCT_ADOPTION AS
    SELECT
        b.ACCOUNT_ID,
        b.ACCOUNT_NAME,
        a.PRODUCT_CATEGORY,
        a.USE_CASE,
        a.FEATURE,
        MIN(a.GENERAL_DATE)  AS FIRST_USE_DATE,
        MAX(a.GENERAL_DATE)  AS LAST_USE_DATE,
        SUM(CASE WHEN a.GENERAL_DATE >= DATEADD(''day'', -90, CURRENT_DATE())
            THEN a.REVENUE ELSE 0 END) AS TOTAL_REVENUE_90D,
        DATEDIFF(''day'', MIN(a.GENERAL_DATE), CURRENT_DATE()) AS DAYS_SINCE_FIRST_USE,
        (MIN(a.GENERAL_DATE) >= DATEADD(''day'', -30, CURRENT_DATE())) AS IS_NEW_30D,
        (MAX(a.GENERAL_DATE) >= DATEADD(''day'', -30, CURRENT_DATE())) AS IS_ACTIVE_30D,
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS REFRESHED_AT
    FROM SALES.RAVEN.A360_DAILY_ACCOUNT_PRODUCT_CATEGORY_REVENUE a
    JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS b
        ON b.ACCOUNT_ID = a.SALESFORCE_ACCOUNT_ID
    GROUP BY b.ACCOUNT_ID, b.ACCOUNT_NAME, a.PRODUCT_CATEGORY, a.USE_CASE, a.FEATURE;

    RETURN ''BKMNG_A360_PRODUCT_ADOPTION refreshed: ''
        || (SELECT COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_A360_PRODUCT_ADOPTION)
        || '' rows across ''
        || (SELECT COUNT(DISTINCT ACCOUNT_ID) FROM TEMP.JUSDAVIS.BKMNG_A360_PRODUCT_ADOPTION)
        || '' accounts'';
END;
';
