-- PROCEDURE: TEMP.JUSDAVIS.SP_REFRESH_BKMNG_EMAIL_ACTIVITY()  |  created: 2026-04-08 01:24:29.101000+00:00

CREATE OR REPLACE PROCEDURE "SP_REFRESH_BKMNG_EMAIL_ACTIVITY"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    TRUNCATE TABLE TEMP.JUSDAVIS.BKMNG_EMAIL_ACTIVITY;
    INSERT INTO TEMP.JUSDAVIS.BKMNG_EMAIL_ACTIVITY
        (ACCOUNT_ID, ACCOUNT_NAME, ACE_ASSIGNED,
         EMAILS_LAST_7D, EMAILS_LAST_14D, EMAILS_LAST_30D, EMAILS_LAST_90D,
         LAST_EMAIL_DATE, EMAILS_OUTBOUND_30D, EMAILS_INBOUND_30D,
         AVG_WEEKLY_EMAIL_FREQUENCY, EMAIL_TREND, REFRESHED_AT)
    SELECT
        b.ACCOUNT_ID,
        b.ACCOUNT_NAME,
        b.ACE_ASSIGNED,
        SUM(CASE WHEN r.ACTIVITY_DATE >= DATEADD(''day'', -7,  CURRENT_DATE()) THEN 1 ELSE 0 END),
        SUM(CASE WHEN r.ACTIVITY_DATE >= DATEADD(''day'', -14, CURRENT_DATE()) THEN 1 ELSE 0 END),
        SUM(CASE WHEN r.ACTIVITY_DATE >= DATEADD(''day'', -30, CURRENT_DATE()) THEN 1 ELSE 0 END),
        SUM(CASE WHEN r.ACTIVITY_DATE >= DATEADD(''day'', -90, CURRENT_DATE()) THEN 1 ELSE 0 END),
        MAX(r.ACTIVITY_DATE),
        SUM(CASE WHEN r.ACTIVITY_DATE >= DATEADD(''day'', -30, CURRENT_DATE())
                  AND LOWER(r.SUBJECT) LIKE ''[sent]%'' THEN 1 ELSE 0 END),
        SUM(CASE WHEN r.ACTIVITY_DATE >= DATEADD(''day'', -30, CURRENT_DATE())
                  AND LOWER(r.SUBJECT) NOT LIKE ''[sent]%'' THEN 1 ELSE 0 END),
        ROUND(SUM(CASE WHEN r.ACTIVITY_DATE >= DATEADD(''day'', -30, CURRENT_DATE()) THEN 1 ELSE 0 END) / 4.3, 1),
        CASE
            WHEN SUM(CASE WHEN r.ACTIVITY_DATE >= DATEADD(''day'', -14, CURRENT_DATE()) THEN 1 ELSE 0 END) >
                 SUM(CASE WHEN r.ACTIVITY_DATE >= DATEADD(''day'', -28, CURRENT_DATE())
                          AND r.ACTIVITY_DATE <  DATEADD(''day'', -14, CURRENT_DATE()) THEN 1 ELSE 0 END) * 1.25
                THEN ''increasing''
            WHEN SUM(CASE WHEN r.ACTIVITY_DATE >= DATEADD(''day'', -14, CURRENT_DATE()) THEN 1 ELSE 0 END) <
                 SUM(CASE WHEN r.ACTIVITY_DATE >= DATEADD(''day'', -28, CURRENT_DATE())
                          AND r.ACTIVITY_DATE <  DATEADD(''day'', -14, CURRENT_DATE()) THEN 1 ELSE 0 END) * 0.75
                THEN ''declining''
            ELSE ''stable''
        END,
        CURRENT_TIMESTAMP()
    FROM SALES.RAVEN.ALL_ENGAGEMENTS_PREPED_VIEW r
    INNER JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS b ON b.ACCOUNT_ID = r.SALESFORCE_ACCOUNT_ID
    WHERE r.TYPE = ''EMAIL''
      AND r.ACTIVITY_DATE >= DATEADD(''day'', -90, CURRENT_DATE())
    GROUP BY b.ACCOUNT_ID, b.ACCOUNT_NAME, b.ACE_ASSIGNED;
    RETURN ''Done: '' || (SELECT COUNT(*)::VARCHAR FROM TEMP.JUSDAVIS.BKMNG_EMAIL_ACTIVITY) || '' accounts with email data'';
END;
';
