-- PROCEDURE: TEMP.JUSDAVIS.SP_REFRESH_BKMNG_ONT_INTERACTIONS()  |  created: 2026-04-06 18:47:33.735000+00:00

CREATE OR REPLACE PROCEDURE "SP_REFRESH_BKMNG_ONT_INTERACTIONS"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    TRUNCATE TABLE TEMP.JUSDAVIS.BKMNG_ONT_INTERACTIONS;
    INSERT INTO TEMP.JUSDAVIS.BKMNG_ONT_INTERACTIONS
    WITH scoped_calls AS (
        SELECT g.ID, g.GONG_PRIMARY_ACCOUNT_C, a.ACCOUNT_NAME,
               g.GONG_CALL_START_C, g.GONG_TITLE_C,
               g.GONG_CALL_BRIEF_C, g.GONG_CALL_KEY_POINTS_C, g.GONG_CALL_HIGHLIGHTS_NEXT_STEPS_C,
               g.GONG_RELATED_TOPICS_JSON_C, g.GONG_RELATED_TRACKERS_JSON_C,
               g.GONG_PARTICIPANTS_EMAILS_C,
               g.GONG_CALL_DURATION_SEC_C, g.GONG_TALK_TIME_US_C, g.GONG_TALK_TIME_THEM_C,
               g.GONG_CALL_SCORE_C, g.GONG_VIEW_CALL_C
        FROM FIVETRAN.SALESFORCE.GONG_GONG_CALL_C g
        INNER JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS a ON a.ACCOUNT_ID = g.GONG_PRIMARY_ACCOUNT_C
        WHERE g.IS_DELETED = FALSE
    ),
    topics_agg AS (
        SELECT s.ID AS CALL_ID,
               NULLIF(ARRAY_TO_STRING(ARRAY_AGG(DISTINCT CASE WHEN t.VALUE IS NOT NULL THEN t.value:Name::STRING END), '', ''), '''') AS TOPICS
        FROM scoped_calls s
        LEFT JOIN LATERAL FLATTEN(input => TRY_PARSE_JSON(s.GONG_RELATED_TOPICS_JSON_C), OUTER => TRUE) t
        GROUP BY s.ID
    ),
    trackers_agg AS (
        SELECT s.ID AS CALL_ID,
               NULLIF(ARRAY_TO_STRING(ARRAY_AGG(DISTINCT CASE WHEN tr.VALUE IS NOT NULL THEN tr.value:Name::STRING END), '', ''), '''') AS TRACKERS
        FROM scoped_calls s
        LEFT JOIN LATERAL FLATTEN(input => TRY_PARSE_JSON(s.GONG_RELATED_TRACKERS_JSON_C), OUTER => TRUE) tr
        GROUP BY s.ID
    )
    SELECT c.ID, c.GONG_PRIMARY_ACCOUNT_C, c.ACCOUNT_NAME, ''gong_call'',
           c.GONG_CALL_START_C, c.GONG_TITLE_C,
           LEFT(REGEXP_REPLACE(COALESCE(c.GONG_CALL_BRIEF_C,''''), ''<[^>]+>'', ''''), 8000),
           LEFT(REGEXP_REPLACE(COALESCE(c.GONG_CALL_KEY_POINTS_C,''''), ''<[^>]+>'', ''''), 4000),
           LEFT(REGEXP_REPLACE(COALESCE(c.GONG_CALL_HIGHLIGHTS_NEXT_STEPS_C,''''), ''<[^>]+>'', ''''), 4000),
           ta.TOPICS, tr.TRACKERS, c.GONG_PARTICIPANTS_EMAILS_C,
           c.GONG_CALL_DURATION_SEC_C, c.GONG_TALK_TIME_US_C, c.GONG_TALK_TIME_THEM_C,
           c.GONG_CALL_SCORE_C, c.GONG_VIEW_CALL_C, CURRENT_TIMESTAMP()
    FROM scoped_calls c
    LEFT JOIN topics_agg ta ON ta.CALL_ID = c.ID
    LEFT JOIN trackers_agg tr ON tr.CALL_ID = c.ID;
    RETURN ''OK: '' || (SELECT COUNT(*)::VARCHAR FROM TEMP.JUSDAVIS.BKMNG_ONT_INTERACTIONS) || '' rows'';
END;
';
