-- PROCEDURE: TEMP.JUSDAVIS.SP_REFRESH_BKMNG_ONT_ACCOUNTS()  |  created: 2026-04-08 04:55:53.820000+00:00

CREATE OR REPLACE PROCEDURE "SP_REFRESH_BKMNG_ONT_ACCOUNTS"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    CREATE OR REPLACE TABLE TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNTS AS
    WITH contract_cte AS (
        SELECT
            ACCOUNT_ID,
            NET_TCV AS CONTRACT_CAPACITY,
            REV_180D AS TOTAL_CONSUMED_CREDITS,
            GREATEST(0, COALESCE(NET_TCV, 0) - COALESCE(REV_180D, 0)) AS CAPACITY_REMAINING,
            PREDICTED_OVERAGE_DATE,
            CASE WHEN NET_ACV > 0 THEN ROUND(REV_90D * (365.0/90) / NET_ACV * 100, 1) ELSE NULL END AS CONTRACT_UTILIZATION_PCT
        FROM TEMP.JUSDAVIS.BKMNG_A360_CONTRACT
    ),
    consumption_cte AS (
        SELECT ACCOUNT_ID, WOW_PCT_CHANGE, MOM_PCT_CHANGE
        FROM TEMP.JUSDAVIS.BKMNG_A360_CONSUMPTION
    ),
    interaction_agg AS (
        SELECT ACCOUNT_ID,
               COUNT(CASE WHEN INTERACTION_DATE >= DATEADD(''day'',-90,CURRENT_TIMESTAMP()) THEN 1 END) AS TOTAL_GONG_CALLS_90D,
               AVG(CASE WHEN INTERACTION_DATE >= DATEADD(''day'',-90,CURRENT_TIMESTAMP()) THEN CALL_SCORE END) AS AVG_GONG_SCORE_90D,
               MAX(INTERACTION_DATE::DATE) AS LAST_EXTERNAL_INTERACTION_DATE
        FROM TEMP.JUSDAVIS.BKMNG_ONT_INTERACTIONS GROUP BY ACCOUNT_ID
    ),
    uc_agg AS (
        SELECT ACCOUNT_ID,
               COUNT(CASE WHEN STATUS IN (''In Pursuit'',''Implementation'') THEN 1 END) AS ACTIVE_USE_CASE_COUNT,
               COUNT(CASE WHEN STATUS = ''Implementation'' THEN 1 END) AS IMPL_USE_CASE_COUNT,
               COUNT(CASE WHEN STATUS = ''Blocked'' THEN 1 END) AS BLOCKED_USE_CASE_COUNT,
               AVG(MEDDPICC_OVERALL_SCORE) AS AVG_MEDDPICC_SCORE
        FROM TEMP.JUSDAVIS.BKMNG_USE_CASES GROUP BY ACCOUNT_ID
    ),
    base AS (
        SELECT a.*, cr.CONTRACT_UTILIZATION_PCT, cr.TOTAL_CONSUMED_CREDITS, cr.CONTRACT_CAPACITY,
               cr.CAPACITY_REMAINING, cr.PREDICTED_OVERAGE_DATE, cn.WOW_PCT_CHANGE, cn.MOM_PCT_CHANGE,
               ia.TOTAL_GONG_CALLS_90D, ia.AVG_GONG_SCORE_90D, ia.LAST_EXTERNAL_INTERACTION_DATE,
               DATEDIFF(''day'', ia.LAST_EXTERNAL_INTERACTION_DATE, CURRENT_DATE()) AS DAYS_SINCE_LAST_INTERACTION,
               ua.ACTIVE_USE_CASE_COUNT, ua.IMPL_USE_CASE_COUNT, ua.BLOCKED_USE_CASE_COUNT, ua.AVG_MEDDPICC_SCORE
        FROM TEMP.JUSDAVIS.BKMNG_ACCOUNTS a
        LEFT JOIN contract_cte cr ON cr.ACCOUNT_ID = a.ACCOUNT_ID
        LEFT JOIN consumption_cte cn ON cn.ACCOUNT_ID = a.ACCOUNT_ID
        LEFT JOIN interaction_agg ia ON ia.ACCOUNT_ID = a.ACCOUNT_ID
        LEFT JOIN uc_agg ua ON ua.ACCOUNT_ID = a.ACCOUNT_ID
    ),
    health_scored AS (
        SELECT *,
            ROUND((
                LEAST(100, GREATEST(0, 50 + COALESCE(WOW_PCT_CHANGE,0)))        * 0.25 +
                LEAST(100, GREATEST(0, COALESCE(IMPL_USE_CASE_COUNT,0) * 25))   * 0.25 +
                CASE WHEN LAST_EXTERNAL_INTERACTION_DATE IS NULL THEN 0
                     WHEN DAYS_SINCE_LAST_INTERACTION < 7 THEN 100
                     WHEN DAYS_SINCE_LAST_INTERACTION < 14 THEN 75
                     WHEN DAYS_SINCE_LAST_INTERACTION < 30 THEN 40
                     ELSE 10 END                                                 * 0.25 +
                LEAST(100, GREATEST(0, COALESCE(AVG_MEDDPICC_SCORE,50)))        * 0.25
            ), 1) AS HEALTH_SCORE
        FROM base
    ),
    new_adoption_30d_cte AS (
        SELECT ACCOUNT_ID,
               LISTAGG(FEATURE, '', '') WITHIN GROUP (ORDER BY FEATURE) AS NEW_ADOPTION_30D
        FROM TEMP.JUSDAVIS.BKMNG_A360_PRODUCT_ADOPTION
        WHERE IS_NEW_30D = TRUE
        GROUP BY ACCOUNT_ID
    ),
    adoption_signals_cte AS (
        SELECT
            ACCOUNT_ID,
            MAX(CASE WHEN PRODUCT_CATEGORY = ''Data Engineering'' AND USE_CASE = ''Ingestion''       AND IS_ACTIVE_30D THEN 1 ELSE 0 END) AS SIG_PIPELINE,
            MAX(CASE WHEN PRODUCT_CATEGORY = ''Data Engineering'' AND USE_CASE = ''Transformation''  AND IS_ACTIVE_30D THEN 1 ELSE 0 END) AS SIG_TRANSFORMS,
            MAX(CASE WHEN PRODUCT_CATEGORY = ''Analytics''                                         AND IS_ACTIVE_30D THEN 1 ELSE 0 END) AS SIG_BI,
            MAX(CASE WHEN PRODUCT_CATEGORY = ''Platform''         AND USE_CASE = ''Cost Governance'' AND IS_ACTIVE_30D THEN 1 ELSE 0 END) AS SIG_COST,
            MAX(CASE WHEN PRODUCT_CATEGORY = ''Applications & Collaboration''                      AND IS_ACTIVE_30D THEN 1 ELSE 0 END) AS SIG_COLLAB,
            MAX(CASE WHEN PRODUCT_CATEGORY = ''Platform''         AND USE_CASE = ''Observability''   AND IS_ACTIVE_30D THEN 1 ELSE 0 END) AS SIG_OBS,
            MAX(CASE WHEN PRODUCT_CATEGORY = ''AI/ML''                                             AND IS_ACTIVE_30D THEN 1 ELSE 0 END) AS SIG_AIML,
            MAX(CASE WHEN PRODUCT_CATEGORY = ''Transactions''                                      AND IS_ACTIVE_30D THEN 1 ELSE 0 END) AS SIG_SPCS
        FROM TEMP.JUSDAVIS.BKMNG_A360_PRODUCT_ADOPTION
        GROUP BY ACCOUNT_ID
    ),
    meeting_agg AS (
        SELECT ACCOUNT_ID,
               COUNT(CASE WHEN IS_UPCOMING = FALSE AND ACTIVITY_DATE >= DATEADD(''day'', -30, CURRENT_DATE()) THEN 1 END) AS MEETINGS_LAST_30D,
               COUNT(CASE WHEN IS_UPCOMING = TRUE  AND ACTIVITY_DATE <= DATEADD(''day'',  5, CURRENT_DATE()) THEN 1 END) AS UPCOMING_MEETINGS_5D,
               MAX(CASE WHEN IS_UPCOMING = FALSE THEN ACTIVITY_DATE END) AS LAST_MEETING_DATE
        FROM TEMP.JUSDAVIS.BKMNG_MEETING_ACTIVITY
        GROUP BY ACCOUNT_ID
    )
    SELECT
        hs.*,
        CASE WHEN hs.HEALTH_SCORE>=70 THEN ''accelerating''
             WHEN hs.HEALTH_SCORE>=45 THEN ''steady''
             WHEN hs.HEALTH_SCORE>=25 THEN ''decelerating''
             ELSE ''stalled'' END AS MOMENTUM,
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS ONT_REFRESHED_AT,
        COALESCE(ads.SIG_PIPELINE, 0)   AS SIG_PIPELINE,
        COALESCE(ads.SIG_TRANSFORMS, 0) AS SIG_TRANSFORMS,
        COALESCE(ads.SIG_BI, 0)         AS SIG_BI,
        COALESCE(ads.SIG_COST, 0)       AS SIG_COST,
        COALESCE(ads.SIG_COLLAB, 0)     AS SIG_COLLAB,
        COALESCE(ads.SIG_OBS, 0)        AS SIG_OBS,
        COALESCE(ads.SIG_AIML, 0)       AS SIG_AIML,
        COALESCE(ads.SIG_SPCS, 0)       AS SIG_SPCS,
        COALESCE(ads.SIG_PIPELINE, 0) + COALESCE(ads.SIG_TRANSFORMS, 0) + COALESCE(ads.SIG_BI, 0)
            + COALESCE(ads.SIG_COST, 0) + COALESCE(ads.SIG_COLLAB, 0) + COALESCE(ads.SIG_OBS, 0)
            + COALESCE(ads.SIG_AIML, 0) + COALESCE(ads.SIG_SPCS, 0) AS ADOPTION_SIGNAL_COUNT,
        NULL::VARCHAR AS ADOPTION_PROFILE,
        NULL::VARCHAR AS MISSING_CATEGORIES,
        na.NEW_ADOPTION_30D,
        COALESCE(ma.MEETINGS_LAST_30D, 0)    AS MEETINGS_LAST_30D,
        COALESCE(ma.UPCOMING_MEETINGS_5D, 0) AS UPCOMING_MEETINGS_5D,
        ma.LAST_MEETING_DATE,
        COALESCE(ea.EMAILS_LAST_30D, 0)      AS EMAILS_LAST_30D,
        ea.LAST_EMAIL_DATE,
        ea.EMAIL_TREND
    FROM health_scored hs
    LEFT JOIN adoption_signals_cte ads ON ads.ACCOUNT_ID = hs.ACCOUNT_ID
    LEFT JOIN new_adoption_30d_cte na  ON na.ACCOUNT_ID  = hs.ACCOUNT_ID
    LEFT JOIN meeting_agg ma           ON ma.ACCOUNT_ID  = hs.ACCOUNT_ID
    LEFT JOIN TEMP.JUSDAVIS.BKMNG_EMAIL_ACTIVITY ea ON ea.ACCOUNT_ID = hs.ACCOUNT_ID;

    RETURN ''OK: '' || (SELECT COUNT(*)::VARCHAR FROM TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNTS) || '' rows'';
END;
';
