-- PROCEDURE: TEMP.JUSDAVIS.SP_REFRESH_BKMNG_ONT_ACCOUNT_COMPETITORS()  |  created: 2026-04-06 18:47:34.477000+00:00

CREATE OR REPLACE PROCEDURE "SP_REFRESH_BKMNG_ONT_ACCOUNT_COMPETITORS"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    TRUNCATE TABLE TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNT_COMPETITORS;
    INSERT INTO TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNT_COMPETITORS
    SELECT g.GONG_PRIMARY_ACCOUNT_C, a.ACCOUNT_NAME, tr.value:Name::STRING,
           SUM(COALESCE(tr.value:Gong__Tracker_Occurrences__c::FLOAT, 1)),
           MAX(g.GONG_CALL_START_C::DATE), CURRENT_TIMESTAMP()
    FROM FIVETRAN.SALESFORCE.GONG_GONG_CALL_C g
    INNER JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS a ON a.ACCOUNT_ID = g.GONG_PRIMARY_ACCOUNT_C
    JOIN LATERAL FLATTEN(input => TRY_PARSE_JSON(g.GONG_RELATED_TRACKERS_JSON_C)) tr
    WHERE g.IS_DELETED = FALSE
      AND g.GONG_CALL_START_C >= DATEADD(''day'', -90, CURRENT_TIMESTAMP())
      AND tr.value:Name IS NOT NULL AND tr.value:Name::STRING != ''''
    GROUP BY 1, 2, 3;
    RETURN ''OK: '' || (SELECT COUNT(*)::VARCHAR FROM TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNT_COMPETITORS) || '' rows'';
END;
';
