-- PROCEDURE: TEMP.JUSDAVIS.SP_REFRESH_BKMNG_ONT_CONTACTS()  |  created: 2026-04-06 19:05:30.119000+00:00

CREATE OR REPLACE PROCEDURE "SP_REFRESH_BKMNG_ONT_CONTACTS"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    TRUNCATE TABLE TEMP.JUSDAVIS.BKMNG_ONT_CONTACTS;
    INSERT INTO TEMP.JUSDAVIS.BKMNG_ONT_CONTACTS
    WITH scoped_contacts AS (
        SELECT c.ID, c.ACCOUNT_ID, c.NAME, c.EMAIL, c.TITLE, c.DEPARTMENT
        FROM FIVETRAN.SALESFORCE.CONTACT c
        INNER JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS a ON a.ACCOUNT_ID = c.ACCOUNT_ID
        WHERE c.IS_DELETED = FALSE AND c.EMAIL IS NOT NULL
    ),
    uc_roles AS (
        SELECT ucr.CONTACT_C AS CONTACT_ID,
               ARRAY_TO_STRING(ARRAY_AGG(DISTINCT ucr.ROLE_C), '', '') AS USE_CASE_ROLES,
               BOOLOR_AGG(ucr.IS_PRIMARY_C)                           AS IS_PRIMARY_ON_USE_CASE,
               BOOLOR_AGG(ucr.IS_PRIMARY_C = TRUE OR LOWER(ucr.ROLE_C) LIKE ''%champion%'') AS IS_CHAMPION
        FROM FIVETRAN.SALESFORCE.USE_CASE_CONTACT_ROLE_C ucr
        WHERE ucr.IS_DELETED = FALSE GROUP BY ucr.CONTACT_C
    ),
    gong_participation AS (
        SELECT LOWER(TRIM(ep.VALUE::STRING)) AS EMAIL,
               COUNT(*)                      AS GONG_CALL_COUNT_90D,
               MAX(i.INTERACTION_DATE::DATE) AS LAST_GONG_CALL_DATE
        FROM TEMP.JUSDAVIS.BKMNG_ONT_INTERACTIONS i,
        LATERAL SPLIT_TO_TABLE(i.PARTICIPANT_EMAILS, '','') ep
        WHERE i.INTERACTION_DATE >= DATEADD(''day'', -90, CURRENT_TIMESTAMP())
          AND ep.VALUE IS NOT NULL AND TRIM(ep.VALUE::STRING) != ''''
        GROUP BY LOWER(TRIM(ep.VALUE::STRING))
    )
    SELECT sc.ID, sc.ACCOUNT_ID, a.ACCOUNT_NAME, sc.NAME, sc.EMAIL, sc.TITLE, sc.DEPARTMENT,
           COALESCE(ur.USE_CASE_ROLES, ''Unknown''), COALESCE(ur.IS_CHAMPION, FALSE),
           COALESCE(ur.IS_PRIMARY_ON_USE_CASE, FALSE), COALESCE(gp.GONG_CALL_COUNT_90D, 0),
           gp.LAST_GONG_CALL_DATE,
           DATEDIFF(''day'', gp.LAST_GONG_CALL_DATE, CURRENT_DATE()),
           CURRENT_TIMESTAMP()
    FROM scoped_contacts sc
    INNER JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS a ON a.ACCOUNT_ID = sc.ACCOUNT_ID
    LEFT JOIN uc_roles ur ON ur.CONTACT_ID = sc.ID
    LEFT JOIN gong_participation gp ON gp.EMAIL = LOWER(TRIM(sc.EMAIL));
    RETURN ''OK: '' || (SELECT COUNT(*)::VARCHAR FROM TEMP.JUSDAVIS.BKMNG_ONT_CONTACTS) || '' rows'';
END;
';
