-- PROCEDURE: TEMP.JUSDAVIS.SP_REFRESH_BKMNG_ONT_ACCOUNT_TOPICS()  |  created: 2026-04-06 18:47:34.232000+00:00

CREATE OR REPLACE PROCEDURE "SP_REFRESH_BKMNG_ONT_ACCOUNT_TOPICS"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    TRUNCATE TABLE TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNT_TOPICS;
    INSERT INTO TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNT_TOPICS
    SELECT g.GONG_PRIMARY_ACCOUNT_C, a.ACCOUNT_NAME, t.value:Name::STRING,
           COUNT(*), MAX(g.GONG_CALL_START_C::DATE),
           AVG(t.value:Gong__Topic_Duration_Sec__c::FLOAT), CURRENT_TIMESTAMP()
    FROM FIVETRAN.SALESFORCE.GONG_GONG_CALL_C g
    INNER JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS a ON a.ACCOUNT_ID = g.GONG_PRIMARY_ACCOUNT_C
    JOIN LATERAL FLATTEN(input => TRY_PARSE_JSON(g.GONG_RELATED_TOPICS_JSON_C)) t
    WHERE g.IS_DELETED = FALSE
      AND g.GONG_CALL_START_C >= DATEADD(''day'', -90, CURRENT_TIMESTAMP())
      AND t.value:Name IS NOT NULL AND t.value:Name::STRING != ''''
    GROUP BY 1, 2, 3;
    RETURN ''OK: '' || (SELECT COUNT(*)::VARCHAR FROM TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNT_TOPICS) || '' rows'';
END;
';
