-- PROCEDURE: TEMP.JUSDAVIS.SP_REFRESH_BKMNG_MEETING_ACTIVITY()  |  created: 2026-04-08 01:24:28.151000+00:00

CREATE OR REPLACE PROCEDURE "SP_REFRESH_BKMNG_MEETING_ACTIVITY"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    TRUNCATE TABLE TEMP.JUSDAVIS.BKMNG_MEETING_ACTIVITY;
    INSERT INTO TEMP.JUSDAVIS.BKMNG_MEETING_ACTIVITY
        (ACTIVITY_ID, ACCOUNT_ID, ACCOUNT_NAME, ACE_ASSIGNED, SUBJECT,
         ACTIVITY_DATE, OWNER_ID, PARTICIPANT_NAMES, IS_UPCOMING,
         TAKEAWAYS, IS_PAIN_POINTS, IS_NEXT_STEPS, IS_COMPETITOR, REFRESHED_AT)
    SELECT
        r.ACTIVITY_ID,
        b.ACCOUNT_ID,
        b.ACCOUNT_NAME,
        b.ACE_ASSIGNED,
        r.SUBJECT,
        r.ACTIVITY_DATE,
        r.OWNER_ID,
        r.PARTICIPANT_NAMES,
        CASE WHEN r.ACTIVITY_DATE >= CURRENT_DATE() THEN TRUE ELSE FALSE END,
        r.TAKEAWAYS,
        CASE WHEN TRY_CAST(r.IS_PAIN_POINTS::VARCHAR AS BOOLEAN) = TRUE THEN TRUE ELSE FALSE END,
        CASE WHEN TRY_CAST(r.IS_NEXT_STEPS::VARCHAR AS BOOLEAN) = TRUE THEN TRUE ELSE FALSE END,
        CASE WHEN TRY_CAST(r.IS_COMPETITOR::VARCHAR AS BOOLEAN) = TRUE THEN TRUE ELSE FALSE END,
        CURRENT_TIMESTAMP()
    FROM SALES.RAVEN.ALL_ENGAGEMENTS_PREPED_VIEW r
    INNER JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS b ON b.ACCOUNT_ID = r.SALESFORCE_ACCOUNT_ID
    WHERE r.TYPE = ''MEETING''
      AND r.ACTIVITY_DATE >= DATEADD(''day'', -90, CURRENT_DATE())
      AND r.ACTIVITY_DATE < DATEADD(''day'', 21, CURRENT_DATE());
    RETURN ''Done: '' || (SELECT COUNT(*)::VARCHAR FROM TEMP.JUSDAVIS.BKMNG_MEETING_ACTIVITY) || '' meetings'';
END;
';
