-- PROCEDURE: TEMP.JUSDAVIS.SP_REFRESH_BKMNG_ONT_USE_CASES()  |  created: 2026-04-06 18:48:31.713000+00:00

CREATE OR REPLACE PROCEDURE "SP_REFRESH_BKMNG_ONT_USE_CASES"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    TRUNCATE TABLE TEMP.JUSDAVIS.BKMNG_ONT_USE_CASES;
    INSERT INTO TEMP.JUSDAVIS.BKMNG_ONT_USE_CASES
    WITH stage_history AS (
        SELECT PARENT_ID_C AS USE_CASE_ID, MAX(CREATED_DATE) AS LAST_STAGE_CHANGE_DATE
        FROM FIVETRAN.SALESFORCE.USE_CASE_HISTORY_C WHERE FIELD_C=''Stage__c'' AND IS_DELETED=FALSE
        GROUP BY PARENT_ID_C
    ),
    days_in_stage AS (
        SELECT uc.USE_CASE_ID, DATEDIFF(''day'', sh.LAST_STAGE_CHANGE_DATE, CURRENT_DATE()) AS DAYS_IN_CURRENT_STAGE
        FROM TEMP.JUSDAVIS.BKMNG_USE_CASES uc LEFT JOIN stage_history sh ON sh.USE_CASE_ID=uc.USE_CASE_ID
    ),
    portfolio_median AS (
        SELECT uc.STAGE, MEDIAN(dis.DAYS_IN_CURRENT_STAGE) AS MEDIAN_DAYS_IN_STAGE
        FROM TEMP.JUSDAVIS.BKMNG_USE_CASES uc JOIN days_in_stage dis ON dis.USE_CASE_ID=uc.USE_CASE_ID
        WHERE uc.STATUS IN (''In Pursuit'',''Implementation'') AND dis.DAYS_IN_CURRENT_STAGE IS NOT NULL
        GROUP BY uc.STAGE
    ),
    team_members_cte AS (
        SELECT uct.USE_CASE_C,
               ARRAY_TO_STRING(ARRAY_COMPACT(ARRAY_AGG(DISTINCT
                   CASE WHEN u.NAME IS NOT NULL THEN u.NAME||'' (''||uct.TEAM_ROLE_C||'')'' ELSE NULL END
               )),''; '') AS TEAM_MEMBERS
        FROM FIVETRAN.SALESFORCE.USE_CASE_TEAM_C uct
        LEFT JOIN FIVETRAN.SALESFORCE.USER u ON u.ID=uct.USER_C AND u._FIVETRAN_DELETED=FALSE
        WHERE uct.IS_DELETED=FALSE GROUP BY uct.USE_CASE_C
    ),
    champions_cte AS (
        SELECT ACCOUNT_ID, NAME AS PRIMARY_CONTACT_NAME, EMAIL AS PRIMARY_CONTACT_EMAIL
        FROM TEMP.JUSDAVIS.BKMNG_ONT_CONTACTS WHERE IS_CHAMPION=TRUE
        QUALIFY ROW_NUMBER() OVER (PARTITION BY ACCOUNT_ID ORDER BY GONG_CALL_COUNT_90D DESC, DAYS_SINCE_LAST_CALL ASC) = 1
    ),
    related_calls_30d AS (
        SELECT ACCOUNT_ID, COUNT(*) AS RELATED_GONG_CALLS_30D
        FROM TEMP.JUSDAVIS.BKMNG_ONT_INTERACTIONS
        WHERE INTERACTION_DATE >= DATEADD(''day'',-30,CURRENT_TIMESTAMP()) GROUP BY ACCOUNT_ID
    )
    SELECT uc.*,
           dis.DAYS_IN_CURRENT_STAGE,
           CASE WHEN dis.DAYS_IN_CURRENT_STAGE IS NULL OR pm.MEDIAN_DAYS_IN_STAGE IS NULL THEN ''normal''
                WHEN dis.DAYS_IN_CURRENT_STAGE > pm.MEDIAN_DAYS_IN_STAGE*1.5 THEN ''slow''
                WHEN dis.DAYS_IN_CURRENT_STAGE < pm.MEDIAN_DAYS_IN_STAGE*0.5 THEN ''fast''
                ELSE ''normal'' END AS STAGE_VELOCITY,
           tm.TEAM_MEMBERS, ch.PRIMARY_CONTACT_NAME, ch.PRIMARY_CONTACT_EMAIL,
           COALESCE(rc.RELATED_GONG_CALLS_30D,0), CURRENT_TIMESTAMP()
    FROM TEMP.JUSDAVIS.BKMNG_USE_CASES uc
    LEFT JOIN days_in_stage dis ON dis.USE_CASE_ID=uc.USE_CASE_ID
    LEFT JOIN portfolio_median pm ON pm.STAGE=uc.STAGE
    LEFT JOIN team_members_cte tm ON tm.USE_CASE_C=uc.USE_CASE_ID
    LEFT JOIN champions_cte ch ON ch.ACCOUNT_ID=uc.ACCOUNT_ID
    LEFT JOIN related_calls_30d rc ON rc.ACCOUNT_ID=uc.ACCOUNT_ID;
    RETURN ''OK: '' || (SELECT COUNT(*)::VARCHAR FROM TEMP.JUSDAVIS.BKMNG_ONT_USE_CASES) || '' rows'';
END;
';
