-- PROCEDURE: TEMP.JUSDAVIS.SP_REFRESH_BKMNG_CONSUMPTION_TRENDS()  |  created: 2026-04-04 02:27:42.477000+00:00

CREATE OR REPLACE PROCEDURE "SP_REFRESH_BKMNG_CONSUMPTION_TRENDS"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    TRUNCATE TABLE TEMP.JUSDAVIS.BKMNG_CONSUMPTION_TRENDS;
    INSERT INTO TEMP.JUSDAVIS.BKMNG_CONSUMPTION_TRENDS (
        ACCOUNT_ID, PERIOD_TYPE, PERIOD_START, PERIOD_REVENUE, PERIOD_CREDITS,
        DAYS_IN_PERIOD, IS_COMPLETE_PERIOD, PREV_PERIOD_REVENUE, PCT_CHANGE,
        ROLLING_4_PERIOD_AVG_REVENUE, PREV_ROLLING_4_PERIOD_AVG_REVENUE,
        ROLLING_PCT_CHANGE, REFRESHED_AT
    )
    WITH daily AS (
        SELECT
            f.SALESFORCE_ACCOUNT_ID,
            f.GENERAL_DATE,
            f.REVENUE,
            f.TOTAL_CREDITS
        FROM SALES.REPORTING.FACT_CONTRACT_REVENUE_DAILY f
        INNER JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS a ON a.ACCOUNT_ID = f.SALESFORCE_ACCOUNT_ID
        WHERE f.IS_FUTURE = FALSE
    ),
    periods AS (
        SELECT
            SALESFORCE_ACCOUNT_ID,
            ''WEEK'' AS PERIOD_TYPE,
            DATE_TRUNC(''WEEK'', GENERAL_DATE)::DATE AS PERIOD_START,
            SUM(REVENUE) AS PERIOD_REVENUE,
            SUM(TOTAL_CREDITS) AS PERIOD_CREDITS,
            COUNT(DISTINCT GENERAL_DATE) AS DAYS_IN_PERIOD,
            7 AS EXPECTED_DAYS
        FROM daily
        GROUP BY 1, 3
        UNION ALL
        SELECT
            SALESFORCE_ACCOUNT_ID,
            ''MONTH'' AS PERIOD_TYPE,
            DATE_TRUNC(''MONTH'', GENERAL_DATE)::DATE AS PERIOD_START,
            SUM(REVENUE) AS PERIOD_REVENUE,
            SUM(TOTAL_CREDITS) AS PERIOD_CREDITS,
            COUNT(DISTINCT GENERAL_DATE) AS DAYS_IN_PERIOD,
            DAYOFMONTH(LAST_DAY(DATE_TRUNC(''MONTH'', GENERAL_DATE)::DATE)) AS EXPECTED_DAYS
        FROM daily
        GROUP BY 1, 3
    ),
    with_lag AS (
        SELECT
            SALESFORCE_ACCOUNT_ID,
            PERIOD_TYPE,
            PERIOD_START,
            ROUND(PERIOD_REVENUE, 2)   AS PERIOD_REVENUE,
            ROUND(PERIOD_CREDITS, 2)   AS PERIOD_CREDITS,
            DAYS_IN_PERIOD,
            DAYS_IN_PERIOD >= EXPECTED_DAYS AS IS_COMPLETE_PERIOD,
            ROUND(LAG(PERIOD_REVENUE) OVER (
                PARTITION BY SALESFORCE_ACCOUNT_ID, PERIOD_TYPE ORDER BY PERIOD_START
            ), 2) AS PREV_PERIOD_REVENUE,
            ROUND(CASE
                WHEN LAG(PERIOD_REVENUE) OVER (
                    PARTITION BY SALESFORCE_ACCOUNT_ID, PERIOD_TYPE ORDER BY PERIOD_START
                ) > 0
                THEN ((PERIOD_REVENUE - LAG(PERIOD_REVENUE) OVER (
                    PARTITION BY SALESFORCE_ACCOUNT_ID, PERIOD_TYPE ORDER BY PERIOD_START
                )) / LAG(PERIOD_REVENUE) OVER (
                    PARTITION BY SALESFORCE_ACCOUNT_ID, PERIOD_TYPE ORDER BY PERIOD_START
                )) * 100
            END, 1) AS PCT_CHANGE,
            ROUND(AVG(PERIOD_REVENUE) OVER (
                PARTITION BY SALESFORCE_ACCOUNT_ID, PERIOD_TYPE ORDER BY PERIOD_START
                ROWS BETWEEN 3 PRECEDING AND CURRENT ROW
            ), 2) AS ROLLING_4_PERIOD_AVG_REVENUE
        FROM periods
    )
    SELECT
        SALESFORCE_ACCOUNT_ID AS ACCOUNT_ID,
        PERIOD_TYPE,
        PERIOD_START,
        PERIOD_REVENUE,
        PERIOD_CREDITS,
        DAYS_IN_PERIOD,
        IS_COMPLETE_PERIOD,
        PREV_PERIOD_REVENUE,
        PCT_CHANGE,
        ROLLING_4_PERIOD_AVG_REVENUE,
        ROUND(LAG(ROLLING_4_PERIOD_AVG_REVENUE) OVER (
            PARTITION BY SALESFORCE_ACCOUNT_ID, PERIOD_TYPE ORDER BY PERIOD_START
        ), 2) AS PREV_ROLLING_4_PERIOD_AVG_REVENUE,
        ROUND(CASE
            WHEN LAG(ROLLING_4_PERIOD_AVG_REVENUE) OVER (
                PARTITION BY SALESFORCE_ACCOUNT_ID, PERIOD_TYPE ORDER BY PERIOD_START
            ) > 0
            THEN ((ROLLING_4_PERIOD_AVG_REVENUE - LAG(ROLLING_4_PERIOD_AVG_REVENUE) OVER (
                PARTITION BY SALESFORCE_ACCOUNT_ID, PERIOD_TYPE ORDER BY PERIOD_START
            )) / LAG(ROLLING_4_PERIOD_AVG_REVENUE) OVER (
                PARTITION BY SALESFORCE_ACCOUNT_ID, PERIOD_TYPE ORDER BY PERIOD_START
            )) * 100
        END, 1) AS ROLLING_PCT_CHANGE,
        CURRENT_TIMESTAMP() AS REFRESHED_AT
    FROM with_lag;
    RETURN ''OK'';
END;
';
