-- PROCEDURE: TEMP.JUSDAVIS.SP_REFRESH_BKMNG_ADOPTION_SIGNALS()  |  created: 2026-04-06 21:03:09.188000+00:00

CREATE OR REPLACE PROCEDURE "SP_REFRESH_BKMNG_ADOPTION_SIGNALS"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    CREATE OR REPLACE TABLE TEMP.JUSDAVIS.BKMNG_ADOPTION_SIGNALS AS
    WITH acct_map AS (
        SELECT DISTINCT
            r.SALESFORCE_ACCOUNT_ID,
            r.SNOWFLAKE_ACCOUNT_ID::INT AS SNOWFLAKE_ACCOUNT_ID
        FROM SNOWHOUSE.PRODUCT.RELEVANT_SUBSCRIPTION_DAILY_RECORDS r
        JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS b ON b.ACCOUNT_ID = r.SALESFORCE_ACCOUNT_ID
        WHERE r.SNOWFLAKE_ACCOUNT_ID IS NOT NULL
    ),
    -- Unique Salesforce account IDs for signal iteration
    sf_accts AS (
        SELECT DISTINCT SALESFORCE_ACCOUNT_ID FROM acct_map
    ),
    -- Pick one (min) Snowflake ID per Salesforce account for display
    acct_primary AS (
        SELECT SALESFORCE_ACCOUNT_ID, MIN(SNOWFLAKE_ACCOUNT_ID) AS SNOWFLAKE_ACCOUNT_ID
        FROM acct_map
        GROUP BY SALESFORCE_ACCOUNT_ID
    ),
    usage_90d AS (
        SELECT
            m.SALESFORCE_ACCOUNT_ID,
            u.FEATURE
        FROM SNOWHOUSE.PRODUCT.USAGE_TRACKING_SUMMARY u
        JOIN acct_map m ON m.SNOWFLAKE_ACCOUNT_ID = u.ACCOUNT_ID
        WHERE u.DS >= DATEADD(''day'', -90, CURRENT_DATE())
        GROUP BY m.SALESFORCE_ACCOUNT_ID, u.FEATURE
    ),
    compute_90d AS (
        SELECT
            m.SALESFORCE_ACCOUNT_ID,
            c.SERVICE_TYPE,
            SUM(c.BILLED_CREDITS) AS BILLED_CREDITS
        FROM SNOWHOUSE.PRODUCT.COMPUTE_SERVICE_ACCOUNT_USAGE c
        JOIN acct_map m ON m.SNOWFLAKE_ACCOUNT_ID = c.ACCOUNT_ID
        WHERE c.DS >= DATEADD(''day'', -90, CURRENT_DATE())
        GROUP BY m.SALESFORCE_ACCOUNT_ID, c.SERVICE_TYPE
    ),
    signals AS (
        SELECT
            sa.SALESFORCE_ACCOUNT_ID AS ACCOUNT_ID,
            CASE WHEN EXISTS (
                SELECT 1 FROM usage_90d u WHERE u.SALESFORCE_ACCOUNT_ID = sa.SALESFORCE_ACCOUNT_ID
                AND u.FEATURE IN (''PIPE'', ''COPY_HISTORY'', ''SYSTEM$STREAM_HAS_DATA'')
            ) OR EXISTS (
                SELECT 1 FROM compute_90d c WHERE c.SALESFORCE_ACCOUNT_ID = sa.SALESFORCE_ACCOUNT_ID
                AND c.SERVICE_TYPE IN (''USER_SCHEDULED_TASK'')
            ) THEN 1 ELSE 0 END AS SIG_PIPELINE,
            CASE WHEN EXISTS (
                SELECT 1 FROM usage_90d u WHERE u.SALESFORCE_ACCOUNT_ID = sa.SALESFORCE_ACCOUNT_ID
                AND u.FEATURE IN (''DYNAMIC_TABLES'', ''DYNAMIC_TABLES_SCAN'', ''DYNAMIC_TABLE_GRAPH_HISTORY'', ''DYNAMIC_PIVOT'')
            ) OR EXISTS (
                SELECT 1 FROM compute_90d c WHERE c.SALESFORCE_ACCOUNT_ID = sa.SALESFORCE_ACCOUNT_ID
                AND c.SERVICE_TYPE IN (''MATERIALIZED_VIEW_REFRESH'')
            ) THEN 1 ELSE 0 END AS SIG_TRANSFORMS,
            CASE WHEN EXISTS (
                SELECT 1 FROM usage_90d u WHERE u.SALESFORCE_ACCOUNT_ID = sa.SALESFORCE_ACCOUNT_ID
                AND u.FEATURE IN (''SYSTEM$SHOW_STREAMLITS_IN_ACCOUNT'', ''SYSTEM$STREAMLIT_BOOTSTRAP'',
                                  ''SYSTEM$LOG_STREAMLIT_TELEMETRY'', ''SYSTEM$GENERATE_STREAMLIT_TOKEN'',
                                  ''SYSTEM$GENERATE_STREAMLIT_URL_FROM_NAME'', ''SYSTEM$STREAMLIT_RELOAD'')
            ) THEN 1 ELSE 0 END AS SIG_BI,
            CASE WHEN EXISTS (
                SELECT 1 FROM usage_90d u WHERE u.SALESFORCE_ACCOUNT_ID = sa.SALESFORCE_ACCOUNT_ID
                AND u.FEATURE IN (''BUDGET_CORE_BUNDLE_INSTANCE_EXECUTE'', ''SYSTEM$SHOW_BUDGET_DETAILS_IN_ACCOUNT'',
                                  ''SYSTEM$SHOW_BUDGETS_IN_ACCOUNT'', ''WAREHOUSE_METERING_HISTORY'')
            ) THEN 1 ELSE 0 END AS SIG_COST,
            CASE WHEN EXISTS (
                SELECT 1 FROM usage_90d u WHERE u.SALESFORCE_ACCOUNT_ID = sa.SALESFORCE_ACCOUNT_ID
                AND u.FEATURE IN (''SYSTEM$BULK_GET_LISTINGS'', ''SYSTEM$SHOW_INBOUND_SHARES'',
                                  ''SYSTEM$SHOW_OUTBOUND_SHARES'', ''SYSTEM$SHOW_LISTINGS_IN_ALL_PRIVATE_DATA_EXCHANGES'',
                                  ''SYSTEM$SHOW_AVAILABLE_LISTINGS_IN_PUBLIC_DATA_EXCHANGES'')
            ) OR EXISTS (
                SELECT 1 FROM compute_90d c WHERE c.SALESFORCE_ACCOUNT_ID = sa.SALESFORCE_ACCOUNT_ID
                AND c.SERVICE_TYPE IN (''REPLICATION_GROUP_REFRESH'', ''DATABASE_REFRESH'')
            ) THEN 1 ELSE 0 END AS SIG_COLLAB,
            CASE WHEN EXISTS (
                SELECT 1 FROM usage_90d u WHERE u.SALESFORCE_ACCOUNT_ID = sa.SALESFORCE_ACCOUNT_ID
                AND u.FEATURE IN (''SYSTEM$GET_METRIC_IDS_FOR_DATA_QUALITY_MONITORING_RESULT'',
                                  ''SYSTEM$GET_TABLE_IDS_FOR_DATA_QUALITY_MONITORING_RESULT'',
                                  ''SYSTEM$GET_SENSITIVE_DATA_MONITORING_SUMMARY'')
            ) OR EXISTS (
                SELECT 1 FROM compute_90d c WHERE c.SALESFORCE_ACCOUNT_ID = sa.SALESFORCE_ACCOUNT_ID
                AND c.SERVICE_TYPE IN (''AUTOMATIC_CLUSTERING'', ''FILE_DEFRAGMENTATION'')
            ) THEN 1 ELSE 0 END AS SIG_OBS,
            CASE WHEN EXISTS (
                SELECT 1 FROM usage_90d u WHERE u.SALESFORCE_ACCOUNT_ID = sa.SALESFORCE_ACCOUNT_ID
                AND u.FEATURE IN (''CORTEX_SEARCH_REFRESH'', ''SYSTEM$CORTEX_MODEL_ACCESSIBLE'',
                                  ''SYSTEM$CORTEX_GENERATE_TABLE_DESCRIPTION'',
                                  ''SYSTEM$CORTEX_ANALYST_LIST_AGENTIC_OPTIMIZATIONS'',
                                  ''SYSTEM$CORTEX_SEARCH_INDEX_BUILD'', ''TRANSLATE'',
                                  ''SYSTEM$CORTEX_ANALYST_RUN_AGENTIC_OPTIMIZATION'')
            ) OR EXISTS (
                SELECT 1 FROM compute_90d c WHERE c.SALESFORCE_ACCOUNT_ID = sa.SALESFORCE_ACCOUNT_ID
                AND c.SERVICE_TYPE IN (''SEARCH_INDEX_REFRESH'')
            ) THEN 1 ELSE 0 END AS SIG_AIML,
            CASE WHEN EXISTS (
                SELECT 1 FROM usage_90d u WHERE u.SALESFORCE_ACCOUNT_ID = sa.SALESFORCE_ACCOUNT_ID
                AND u.FEATURE IN (''SYSTEM$GET_AVAILABLE_SPCS_RUNTIMES'', ''SYSTEM$GET_IMAGE_REPOSITORY_METADATA'',
                                  ''SYSTEM$SPCS_UI_LIST_JOBS'',
                                  ''SYSTEM$ENQUEUE_IMAGE_REPOSITORY_METADATA_FOR_SNOWFS_CONVERSION'')
            ) OR EXISTS (
                SELECT 1 FROM compute_90d c WHERE c.SALESFORCE_ACCOUNT_ID = sa.SALESFORCE_ACCOUNT_ID
                AND c.SERVICE_TYPE IN (''ICEBERG_STORAGE_OPTIMIZATION'')
            ) THEN 1 ELSE 0 END AS SIG_SPCS
        FROM sf_accts sa
    ),
    credits AS (
        SELECT
            SALESFORCE_ACCOUNT_ID,
            SUM(BILLED_CREDITS) AS TOTAL_BILLED_CREDITS_90D
        FROM compute_90d
        GROUP BY SALESFORCE_ACCOUNT_ID
    )
    SELECT
        s.ACCOUNT_ID,
        b.ACCOUNT_NAME,
        ap.SNOWFLAKE_ACCOUNT_ID,
        s.SIG_PIPELINE,
        s.SIG_TRANSFORMS,
        s.SIG_BI,
        s.SIG_COST,
        s.SIG_COLLAB,
        s.SIG_OBS,
        s.SIG_AIML,
        s.SIG_SPCS,
        (s.SIG_PIPELINE + s.SIG_TRANSFORMS + s.SIG_BI + s.SIG_COST
         + s.SIG_COLLAB + s.SIG_OBS + s.SIG_AIML + s.SIG_SPCS) AS SIGNAL_COUNT,
        ARRAY_TO_STRING(ARRAY_COMPACT(ARRAY_CONSTRUCT(
            IFF(s.SIG_PIPELINE = 1, ''Pipeline'', NULL),
            IFF(s.SIG_TRANSFORMS = 1, ''Transforms'', NULL),
            IFF(s.SIG_BI = 1, ''BI'', NULL),
            IFF(s.SIG_COST = 1, ''Cost Gov'', NULL),
            IFF(s.SIG_COLLAB = 1, ''Collab'', NULL),
            IFF(s.SIG_OBS = 1, ''Observability'', NULL),
            IFF(s.SIG_AIML = 1, ''AI/ML'', NULL),
            IFF(s.SIG_SPCS = 1, ''SPCS'', NULL)
        )), '', '') AS ADOPTION_PROFILE,
        ARRAY_TO_STRING(ARRAY_COMPACT(ARRAY_CONSTRUCT(
            IFF(s.SIG_PIPELINE = 0, ''Pipeline'', NULL),
            IFF(s.SIG_TRANSFORMS = 0, ''Transforms'', NULL),
            IFF(s.SIG_BI = 0, ''BI'', NULL),
            IFF(s.SIG_COST = 0, ''Cost Gov'', NULL),
            IFF(s.SIG_COLLAB = 0, ''Collab'', NULL),
            IFF(s.SIG_OBS = 0, ''Observability'', NULL),
            IFF(s.SIG_AIML = 0, ''AI/ML'', NULL),
            IFF(s.SIG_SPCS = 0, ''SPCS'', NULL)
        )), '', '') AS MISSING_CATEGORIES,
        COALESCE(cr.TOTAL_BILLED_CREDITS_90D, 0) AS TOTAL_BILLED_CREDITS_90D,
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS REFRESHED_AT
    FROM signals s
    JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS b ON b.ACCOUNT_ID = s.ACCOUNT_ID
    JOIN acct_primary ap ON ap.SALESFORCE_ACCOUNT_ID = s.ACCOUNT_ID
    LEFT JOIN credits cr ON cr.SALESFORCE_ACCOUNT_ID = s.ACCOUNT_ID;

    RETURN ''BKMNG_ADOPTION_SIGNALS refreshed: '' || (SELECT COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_ADOPTION_SIGNALS) || '' rows'';
END
';
