-- PROCEDURE: TEMP.JUSDAVIS.SP_REFRESH_BKMNG_A360_CONSUMPTION()  |  created: 2026-04-06 22:52:17.975000+00:00

CREATE OR REPLACE PROCEDURE "SP_REFRESH_BKMNG_A360_CONSUMPTION"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    CREATE OR REPLACE TABLE TEMP.JUSDAVIS.BKMNG_A360_CONSUMPTION AS
    WITH daily_rev AS (
        SELECT
            a.SALESFORCE_ACCOUNT_ID AS ACCOUNT_ID,
            a.GENERAL_DATE,
            SUM(a.REVENUE) AS DAILY_REVENUE
        FROM SALES.RAVEN.A360_DAILY_ACCOUNT_PRODUCT_CATEGORY_REVENUE a
        JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS b ON b.ACCOUNT_ID = a.SALESFORCE_ACCOUNT_ID
        WHERE a.GENERAL_DATE >= DATEADD(''day'', -90, CURRENT_DATE())
        GROUP BY a.SALESFORCE_ACCOUNT_ID, a.GENERAL_DATE
    )
    SELECT
        b.ACCOUNT_ID,
        b.ACCOUNT_NAME,
        SUM(CASE WHEN d.GENERAL_DATE >= DATEADD(''day'', -7, CURRENT_DATE()) THEN d.DAILY_REVENUE ELSE 0 END) AS REV_THIS_WEEK,
        SUM(CASE WHEN d.GENERAL_DATE BETWEEN DATEADD(''day'', -14, CURRENT_DATE()) AND DATEADD(''day'', -8, CURRENT_DATE()) THEN d.DAILY_REVENUE ELSE 0 END) AS REV_LAST_WEEK,
        ROUND(
            (SUM(CASE WHEN d.GENERAL_DATE >= DATEADD(''day'', -7, CURRENT_DATE()) THEN d.DAILY_REVENUE ELSE 0 END)
             - SUM(CASE WHEN d.GENERAL_DATE BETWEEN DATEADD(''day'', -14, CURRENT_DATE()) AND DATEADD(''day'', -8, CURRENT_DATE()) THEN d.DAILY_REVENUE ELSE 0 END))
            / NULLIF(SUM(CASE WHEN d.GENERAL_DATE BETWEEN DATEADD(''day'', -14, CURRENT_DATE()) AND DATEADD(''day'', -8, CURRENT_DATE()) THEN d.DAILY_REVENUE ELSE 0 END), 0)
            * 100, 2
        ) AS WOW_PCT_CHANGE,
        SUM(CASE WHEN d.GENERAL_DATE >= DATEADD(''day'', -30, CURRENT_DATE()) THEN d.DAILY_REVENUE ELSE 0 END) AS REV_THIS_MONTH,
        SUM(CASE WHEN d.GENERAL_DATE BETWEEN DATEADD(''day'', -60, CURRENT_DATE()) AND DATEADD(''day'', -31, CURRENT_DATE()) THEN d.DAILY_REVENUE ELSE 0 END) AS REV_LAST_MONTH,
        ROUND(
            (SUM(CASE WHEN d.GENERAL_DATE >= DATEADD(''day'', -30, CURRENT_DATE()) THEN d.DAILY_REVENUE ELSE 0 END)
             - SUM(CASE WHEN d.GENERAL_DATE BETWEEN DATEADD(''day'', -60, CURRENT_DATE()) AND DATEADD(''day'', -31, CURRENT_DATE()) THEN d.DAILY_REVENUE ELSE 0 END))
            / NULLIF(SUM(CASE WHEN d.GENERAL_DATE BETWEEN DATEADD(''day'', -60, CURRENT_DATE()) AND DATEADD(''day'', -31, CURRENT_DATE()) THEN d.DAILY_REVENUE ELSE 0 END), 0)
            * 100, 2
        ) AS MOM_PCT_CHANGE,
        SUM(d.DAILY_REVENUE) AS REV_90D,
        COUNT(DISTINCT CASE WHEN d.GENERAL_DATE >= DATEADD(''day'', -30, CURRENT_DATE()) THEN d.GENERAL_DATE END) AS ACTIVE_DAYS_30D,
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS REFRESHED_AT
    FROM TEMP.JUSDAVIS.BKMNG_ACCOUNTS b
    LEFT JOIN daily_rev d ON d.ACCOUNT_ID = b.ACCOUNT_ID
    GROUP BY b.ACCOUNT_ID, b.ACCOUNT_NAME;

    RETURN ''BKMNG_A360_CONSUMPTION refreshed: '' || (SELECT COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_A360_CONSUMPTION) || '' rows, '' || (SELECT COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_A360_CONSUMPTION WHERE WOW_PCT_CHANGE IS NOT NULL) || '' with WoW data'';
END
';
