-- PROCEDURE: TEMP.JUSDAVIS.SP_REFRESH_BKMNG_ONT_OPPORTUNITIES()  |  created: 2026-04-06 18:47:54.818000+00:00

CREATE OR REPLACE PROCEDURE "SP_REFRESH_BKMNG_ONT_OPPORTUNITIES"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    TRUNCATE TABLE TEMP.JUSDAVIS.BKMNG_ONT_OPPORTUNITIES;
    INSERT INTO TEMP.JUSDAVIS.BKMNG_ONT_OPPORTUNITIES
    SELECT o.ID, o.ACCOUNT_ID, a.ACCOUNT_NAME, o.NAME, o.STAGE_NAME, o.CLOSE_DATE, o.AMOUNT,
           LEFT(o.SE_COMMENTS_C, 4000), LEFT(o.PS_T_COMMENTS_C, 4000),
           LEFT(o.DECISION_CRITERIA_C, 2000), CURRENT_TIMESTAMP()
    FROM FIVETRAN.SALESFORCE.OPPORTUNITY o
    INNER JOIN TEMP.JUSDAVIS.BKMNG_ACCOUNTS a ON a.ACCOUNT_ID = o.ACCOUNT_ID
    WHERE o.IS_DELETED = FALSE;
    RETURN ''OK: '' || (SELECT COUNT(*)::VARCHAR FROM TEMP.JUSDAVIS.BKMNG_ONT_OPPORTUNITIES) || '' rows'';
END;
';
