-- PROCEDURE: TEMP.JUSDAVIS.SP_REFRESH_BKMNG_SUPPORT_TICKETS()  |  created: 2026-04-07 21:58:10.625000+00:00

CREATE OR REPLACE PROCEDURE "SP_REFRESH_BKMNG_SUPPORT_TICKETS"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    TRUNCATE TABLE TEMP.JUSDAVIS.BKMNG_SUPPORT_TICKETS;

    INSERT INTO TEMP.JUSDAVIS.BKMNG_SUPPORT_TICKETS
        (CASE_ID, CASE_NUMBER, ACCOUNT_ID, ACCOUNT_NAME, STATUS, SEVERITY,
         PRIORITY, CATEGORY, SUB_CATEGORY, COMPONENT, SUBJECT, TYPE,
         IS_ESCALATED, SALES_ESCALATED, IS_CLOSED, CREATED_DATE, CLOSED_DATE,
         DAYS_OPEN, TIME_TO_RESOLUTION_HRS, ESCALATION_STATUS,
         SNOWFLAKE_ACCOUNT, SNOWFLAKE_ACCOUNT_ALIAS, REFRESHED_AT)
    SELECT
        c.ID,
        c.CASE_NUMBER,
        c.ACCOUNT_ID,
        a.ACCOUNT_NAME,
        c.STATUS,
        c.SEVERITY_C,
        c.PRIORITY,
        c.CATEGORY_C,
        c.SUB_CATEGORY_C,
        c.COMPONENT_C,
        c.SUBJECT,
        c.TYPE,
        c.IS_ESCALATED,
        c.SALES_ESCALATED_C,
        c.IS_CLOSED,
        c.CREATED_DATE,
        c.CLOSED_DATE,
        c.DAYS_OPEN_C,
        c.TIME_TO_RESOLUTION_IN_BUSINESS_HRS_C,
        c.ESCALATION_STATUS_C,
        c.SNOWFLAKE_ACCOUNT_C,
        c.SNOWFLAKE_ACCOUNT_ALIAS_C,
        CURRENT_TIMESTAMP()
    FROM FIVETRAN.SALESFORCE.CASE c
    INNER JOIN TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNTS a ON a.ACCOUNT_ID = c.ACCOUNT_ID
    WHERE c._FIVETRAN_ACTIVE = TRUE
      AND c.TYPE = ''Technical Issue''
      AND c.CREATED_DATE >= DATEADD(''day'', -90, CURRENT_DATE())
      AND c.ACCOUNT_ID IS NOT NULL;

    RETURN ''OK: '' || (SELECT COUNT(*)::VARCHAR FROM TEMP.JUSDAVIS.BKMNG_SUPPORT_TICKETS) || '' tickets loaded'';
END
';
