-- PROCEDURE: TEMP.JUSDAVIS.SP_REFRESH_BKMNG_A360_CONTRACT()  |  created: 2026-04-20 21:06:08.136000+00:00

CREATE OR REPLACE PROCEDURE "SP_REFRESH_BKMNG_A360_CONTRACT"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    CREATE OR REPLACE TABLE TEMP.JUSDAVIS.BKMNG_A360_CONTRACT AS
    WITH latest_contract AS (
        SELECT *
        FROM SALES.RAVEN.A360_BOOKINGS_ACV_VIEW
        WHERE VALUE_TYPE = ''actual''
        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY SALESFORCE_ACCOUNT_ID
            ORDER BY CONTRACT_END_DATE DESC, RN DESC
        ) = 1
    ),
    contract_spend AS (
        SELECT
            lc.SALESFORCE_ACCOUNT_ID,
            SUM(r.REVENUE) AS CONTRACT_SPEND
        FROM latest_contract lc
        INNER JOIN SALES.RAVEN.A360_DAILY_ACCOUNT_PRODUCT_CATEGORY_REVENUE r
            ON r.SALESFORCE_ACCOUNT_ID = lc.SALESFORCE_ACCOUNT_ID
            AND r.GENERAL_DATE >= lc.CONTRACT_START_DATE
            AND r.GENERAL_DATE <= CURRENT_DATE()
        GROUP BY lc.SALESFORCE_ACCOUNT_ID
    )
    SELECT
        b.ACCOUNT_ID,
        b.ACCOUNT_NAME,
        c.CONTRACT_START_DATE,
        c.CONTRACT_END_DATE,
        c.NET_ACV,
        c.NET_TCV,
        c.DEAL_TYPE_WITH_CHURN_DESCRIPTION AS DEAL_TYPE,
        (c.DEAL_TYPE_WITH_CHURN_DESCRIPTION = ''Renewal'') AS IS_RENEWAL,
        DATEDIFF(''day'', CURRENT_DATE(), c.CONTRACT_END_DATE) AS DAYS_UNTIL_CONTRACT_END,
        o.DAY_OF_OVERAGE AS PREDICTED_OVERAGE_DATE,
        o.DAYS_TILL_OVERAGE AS DAYS_UNTIL_OVERAGE,
        o.OVERAGE_UNDERAGE_PREDICTION AS PREDICTED_OVERAGE_AMOUNT,
        rr.REV_30 AS REV_30D,
        rr.REV_90 AS REV_90D,
        rr.REV_180 AS REV_180D,
        cs.CONTRACT_SPEND,
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS REFRESHED_AT
    FROM TEMP.JUSDAVIS.BKMNG_ACCOUNTS b
    LEFT JOIN latest_contract c ON c.SALESFORCE_ACCOUNT_ID = b.ACCOUNT_ID
    LEFT JOIN SALES.RAVEN.A360_OVERAGE_UNDERAGE_PREDICTION_VIEW o
        ON o.SALESFORCE_ACCOUNT_ID = b.ACCOUNT_ID
    LEFT JOIN SALES.RAVEN.A360_RUN_RATE_VIEW rr
        ON rr.SALESFORCE_ACCOUNT_ID = b.ACCOUNT_ID
    LEFT JOIN contract_spend cs
        ON cs.SALESFORCE_ACCOUNT_ID = b.ACCOUNT_ID;

    RETURN ''BKMNG_A360_CONTRACT refreshed: '' || (SELECT COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_A360_CONTRACT) || '' rows, '' || (SELECT COUNT(*) FROM TEMP.JUSDAVIS.BKMNG_A360_CONTRACT WHERE NET_ACV IS NOT NULL) || '' with contract data'';
END;
';
