-- PROCEDURE: TEMP.JUSDAVIS.SP_REFRESH_BKMNG_USER_ALERTS()  |  created: 2026-04-15 22:27:37.360000+00:00

CREATE OR REPLACE PROCEDURE "SP_REFRESH_BKMNG_USER_ALERTS"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    INSERT INTO TEMP.JUSDAVIS.BKMNG_USER_ALERTS
        (USER_EMAIL, SIGNAL_ID, SIGNAL_TYPE, ACCOUNT_ID, ACCOUNT_NAME, TEXT, PRIORITY, SOURCE)
    SELECT DISTINCT
        a.ACE_ASSIGNED       AS USER_EMAIL,
        s.SIGNAL_ID,
        s.SIGNAL_TYPE,
        s.ACCOUNT_ID,
        s.ACCOUNT_NAME,
        s.SIGNAL_TEXT        AS TEXT,
        COALESCE(p.PRIORITY_OVERRIDE, s.PRIORITY) AS PRIORITY,
        s.SOURCE
    FROM TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNT_SIGNALS s
    JOIN TEMP.JUSDAVIS.BKMNG_ONT_ACCOUNTS a
      ON a.ACCOUNT_ID = s.ACCOUNT_ID
    LEFT JOIN TEMP.JUSDAVIS.BKMNG_USER_ALERT_PREFERENCES p
      ON p.USER_EMAIL = a.ACE_ASSIGNED
     AND p.SIGNAL_TYPE = s.SIGNAL_TYPE
    WHERE s.ALERT_ELIGIBLE = TRUE
      AND a.ACE_ASSIGNED IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM TEMP.JUSDAVIS.BKMNG_USER_ALERTS ua
          WHERE ua.SIGNAL_ID  = s.SIGNAL_ID
            AND ua.USER_EMAIL = a.ACE_ASSIGNED
      )
      AND (p.ENABLED IS NULL OR p.ENABLED = TRUE);

    RETURN ''OK: '' || (SELECT COUNT(*)::VARCHAR FROM TEMP.JUSDAVIS.BKMNG_USER_ALERTS
                      WHERE IS_DISMISSED = FALSE AND IS_READ = FALSE) || '' active alerts'';
END
';
