-- TABLE: TEMP.JUSDAVIS.T_OD_UNIVERSE_BASE  |  created: 2026-03-24 17:09:09.885000+00:00

create or replace TABLE T_OD_UNIVERSE_BASE (
	SALESFORCE_ACCOUNT_ID VARCHAR(16777216),
	IS_ACTIVE BOOLEAN,
	IS_CONVERTED BOOLEAN,
	SNOWFLAKE_EDITION VARCHAR(16777216),
	HAS_AE BOOLEAN,
	OD_CLOSED_WON_DATE DATE,
	OD_FIRST_USAGE_DATE DATE,
	DAYS_CW_TO_FIRST_USAGE NUMBER(9,0),
	CAPACITY_CONVERSION_DATE DATE,
	SIGNAL_WINDOW_TYPE VARCHAR(14),
	SIGNAL_WINDOW_END_DATE DATE
);
