-- VIEW: TEMP.JUSDAVIS.V_OD_ACCOUNT_SIGNALS  |  created: 2026-03-23 20:51:58.782000+00:00

create or replace view V_OD_ACCOUNT_SIGNALS(
	SALESFORCE_ACCOUNT_ID,
	CONTRACT_START_DATE,
	AE_EMAIL,
	SEGMENT,
	GEO,
	THEATER,
	ACCOUNT_AGE_DAYS,
	HAS_AE,
	TOTAL_CREDITS_90D,
	SIG_PIPELINE,
	SIG_TRANSFORMS,
	SIG_BI,
	SIG_COST,
	SIG_COLLAB,
	SIG_OBS,
	SIG_AIML,
	SIG_SPCS,
	SIGNAL_COUNT
) as
SELECT 
    p.SALESFORCE_ACCOUNT_ID,
    p.CONTRACT_START_DATE,
    p.AE_EMAIL,
    p.SEGMENT,
    p.GEO,
    p.THEATER,
    p.ACCOUNT_AGE_DAYS,
    p.HAS_AE,
    COALESCE(s.TOTAL_CREDITS_90D, 0) as TOTAL_CREDITS_90D,
    COALESCE(s.sig_pipeline, 0) as SIG_PIPELINE,
    COALESCE(s.sig_transforms, 0) as SIG_TRANSFORMS,
    COALESCE(s.sig_bi, 0) as SIG_BI,
    COALESCE(s.sig_cost, 0) as SIG_COST,
    COALESCE(s.sig_collab, 0) as SIG_COLLAB,
    COALESCE(s.sig_obs, 0) as SIG_OBS,
    COALESCE(s.sig_aiml, 0) as SIG_AIML,
    COALESCE(s.sig_spcs, 0) as SIG_SPCS,
    COALESCE(s.sig_pipeline,0) + COALESCE(s.sig_transforms,0) + COALESCE(s.sig_bi,0) + 
    COALESCE(s.sig_cost,0) + COALESCE(s.sig_collab,0) + COALESCE(s.sig_obs,0) + 
    COALESCE(s.sig_aiml,0) + COALESCE(s.sig_spcs,0) as SIGNAL_COUNT
FROM TEMP.JUSDAVIS.V_PURE_OD_ACCOUNTS p
LEFT JOIN (
    SELECT u.SFDC_CUST_ID,
        SUM(u.CREDITS) as TOTAL_CREDITS_90D,
        MAX(CASE WHEN u.PROD_SUBCAT='INGESTION' AND u.PROD_FEATURE IN ('SNOWPIPE','SNOWPIPE KAFKA','SPARK CONNECTOR','NATIVE APP CONNECTOR','OPENFLOW','SNOWPIPE STREAMING V1','SNOWPIPE STREAMING V2','SNOWPIPE STREAMING KAFKA','SNOWPIPE STREAMING DB CONNECTOR') THEN 1 ELSE 0 END) as sig_pipeline,
        MAX(CASE WHEN u.PROD_FEATURE IN ('DT REFRESH','STREAM ACCESS') THEN 1 ELSE 0 END) as sig_transforms,
        MAX(CASE WHEN u.PROD_SUBCAT='BI TOOLS (3P)' OR u.PROD_FEATURE IN ('STREAMLIT','SNOWSIGHT DASHBOARD') THEN 1 ELSE 0 END) as sig_bi,
        MAX(CASE WHEN u.PROD_SUBCAT='COST GOVERNANCE' THEN 1 ELSE 0 END) as sig_cost,
        MAX(CASE WHEN u.PROD_SUBCAT IN ('EXTERNAL COLLABORATION','INTERNAL COLLABORATION','MARKETPLACE') THEN 1 ELSE 0 END) as sig_collab,
        MAX(CASE WHEN u.PROD_SUBCAT='OBSERVABILITY' THEN 1 ELSE 0 END) as sig_obs,
        MAX(CASE WHEN u.PROD_CAT='AI/ML' AND u.PROD_SUBCAT NOT IN ('SI AND AGENTS','UNSTRUCTURED DATA INSIGHTS') THEN 1 ELSE 0 END) as sig_aiml,
        MAX(CASE WHEN u.PROD_FEATURE LIKE '%SPCS%' THEN 1 ELSE 0 END) as sig_spcs
    FROM SALES.CX_INSIGHTS.V_ACCT_PRODUCT_USAGE_DLY u
    WHERE u.USAGE_DATE >= DATEADD('day', -90, CURRENT_DATE)
    GROUP BY u.SFDC_CUST_ID
) s ON s.SFDC_CUST_ID = p.SALESFORCE_ACCOUNT_ID;
