-- VIEW: TEMP.JUSDAVIS.V_PURE_OD_ACCOUNTS  |  created: 2026-03-23 20:51:42.477000+00:00

create or replace view V_PURE_OD_ACCOUNTS(
	SALESFORCE_ACCOUNT_ID,
	CONTRACT_START_DATE,
	AE_EMAIL,
	SEGMENT,
	GEO,
	THEATER,
	ACCOUNT_AGE_DAYS,
	HAS_AE
) as
WITH latest AS (
    SELECT MAX(SNAPSHOT_DATE) as sd FROM FINANCE.CUSTOMER.CONTRACT_SNAPSHOT
),
capacity_accts AS (
    SELECT DISTINCT SALESFORCE_ACCOUNT_ID
    FROM FINANCE.CUSTOMER.CONTRACT_SNAPSHOT, latest
    WHERE SNAPSHOT_DATE = latest.sd AND AGREEMENT_TYPE = 'Capacity'
)
SELECT DISTINCT
    cs.SALESFORCE_ACCOUNT_ID,
    cs.CONTRACT_START_DATE,
    cs.AE_EMAIL,
    cs.SEGMENT,
    cs.GEO,
    cs.THEATER,
    DATEDIFF('day', cs.CONTRACT_START_DATE, CURRENT_DATE) as ACCOUNT_AGE_DAYS,
    CASE WHEN cs.AE_EMAIL IS NOT NULL AND cs.AE_EMAIL != '' THEN 1 ELSE 0 END as HAS_AE
FROM FINANCE.CUSTOMER.CONTRACT_SNAPSHOT cs, latest
WHERE cs.SNAPSHOT_DATE = latest.sd
  AND cs.AGREEMENT_TYPE = 'On Demand'
  AND cs.CONTRACT_STATUS = 'Activated'
  AND cs.SALESFORCE_ACCOUNT_ID NOT IN (SELECT SALESFORCE_ACCOUNT_ID FROM capacity_accts);
