-- TABLE: TEMP.JUSDAVIS.BKMNG_USE_CASE_UPDATES
-- Stores AI-generated weekly use case updates that SEs can copy/paste into Salesforce.
-- One row per USE_CASE_ID (latest suggestion replaces prior).

CREATE TABLE IF NOT EXISTS TEMP.JUSDAVIS.BKMNG_USE_CASE_UPDATES (
    UPDATE_ID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    USE_CASE_ID VARCHAR(16777216) NOT NULL,
    ACCOUNT_ID VARCHAR(16777216),
    USE_CASE_NAME VARCHAR(16777216),
    STAGE VARCHAR(16777216),
    ACE_EMAIL VARCHAR(16777216),
    WEEK_OF DATE,
    UPDATE_TEXT VARCHAR(2000),
    STATUS VARCHAR(16),  -- 'suggested' | 'edited' | 'no_update'
    BASIS_SUMMARY VARCHAR(4000),
    SOURCE_COUNT_NOTES NUMBER,
    SOURCE_COUNT_GONG NUMBER,
    SOURCE_COUNT_TIMELINE NUMBER,
    IS_EDITED BOOLEAN DEFAULT FALSE,
    GENERATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    LAST_MODIFIED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    LAST_MODIFIED_BY VARCHAR(16777216),
    PRIMARY KEY (UPDATE_ID)
);
