-- TABLE: TEMP.JUSDAVIS.BKMNG_SECURITY_POSTURE_OVERRIDES  |  created: 2026-04-16 19:34:07.277000+00:00

create or replace TABLE BKMNG_SECURITY_POSTURE_OVERRIDES (
	ACCOUNT_ID VARCHAR(18) NOT NULL,
	MILESTONE_ID VARCHAR(50) NOT NULL,
	ACE_STATUS VARCHAR(30),
	ACE_NOTES VARCHAR(2000),
	UPDATED_BY VARCHAR(255),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (ACCOUNT_ID, MILESTONE_ID)
);
