-- TABLE: TEMP.JUSDAVIS.BKMNG_USER_CONTEXT  |  created: 2026-04-06 18:21:16.230000+00:00

create or replace TABLE BKMNG_USER_CONTEXT (
	CONTEXT_ID VARCHAR(255) DEFAULT UUID_STRING(),
	ACCOUNT_ID VARCHAR(255),
	ACCOUNT_NAME VARCHAR(255),
	CONTEXT_TYPE VARCHAR(100),
	CONTENT VARCHAR(16777216),
	SOURCE VARCHAR(100) DEFAULT 'manual',
	CREATED_BY VARCHAR(255) WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='EMAIL'),
	CREATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
	IS_ACTIVE BOOLEAN DEFAULT TRUE
)COMMENT='Extensible ad-hoc context store for ACE notes, future Glean/email imports, and manual account annotations. SOURCE values: manual | glean | email_import | meeting_prep'
;
