-- TABLE: TEMP.JUSDAVIS.BKMNG_MANUAL_MEETINGS  |  created: 2026-04-09 23:23:12.597000+00:00

create or replace TABLE BKMNG_MANUAL_MEETINGS (
	MEETING_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
	ACCOUNT_ID VARCHAR(36) NOT NULL,
	ACCOUNT_NAME VARCHAR(512),
	TITLE VARCHAR(512) NOT NULL,
	MEETING_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ATTENDEES VARCHAR(2048),
	NOTES VARCHAR(16384),
	NOTES_ADDED BOOLEAN DEFAULT FALSE,
	CREATED_BY VARCHAR(256) NOT NULL WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='EMAIL'),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	NOTES_SUMMARY VARCHAR(4000),
	SOURCE_TYPE VARCHAR(50) DEFAULT 'meeting',
	primary key (MEETING_ID)
);
