-- TABLE: TEMP.JUSDAVIS.BKMNG_ACCOUNTS  |  created: 2026-04-03 20:53:09.177000+00:00

create or replace TABLE BKMNG_ACCOUNTS (
	ACCOUNT_ID VARCHAR(18) NOT NULL,
	ACCOUNT_NAME VARCHAR(500) NOT NULL,
	INDUSTRY VARCHAR(255),
	REGION VARCHAR(255),
	ACE_USER_ID VARCHAR(18),
	ACE_ASSIGNED VARCHAR(255) WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='EMAIL'),
	ENGAGEMENT_STATUS VARCHAR(100) DEFAULT 'Active',
	STATUS VARCHAR(100) DEFAULT 'Active',
	ACTIVATION_START_DATE DATE,
	TOTAL_CREDITS_ALLOCATED FLOAT,
	ACV FLOAT,
	CONSUMPTION_YTD FLOAT,
	REFRESHED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	LEAD_SE_EMAIL VARCHAR(255) WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='EMAIL'),
	AE_EMAIL VARCHAR(255) WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='EMAIL'),
	AE_NAME VARCHAR(255),
	primary key (ACCOUNT_ID)
);
