-- TABLE: TEMP.JUSDAVIS.BKMNG_ACCOUNT_SETTINGS  |  created: 2026-04-09 23:23:10.586000+00:00

create or replace TABLE BKMNG_ACCOUNT_SETTINGS (
	ACCOUNT_ID VARCHAR(36) NOT NULL,
	NO_RECORDING BOOLEAN DEFAULT FALSE,
	UPDATED_BY VARCHAR(256),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	STATUS VARCHAR(100),
	ENGAGEMENT_STATUS VARCHAR(100),
	ENGAGEMENT_START_DATE DATE,
	ROLLOFF_DATE DATE,
	PRIMARY_ACE_EMAIL VARCHAR(255),
	COVERAGE_ACE_EMAIL VARCHAR(255),
	COVERAGE_UNTIL DATE,
	primary key (ACCOUNT_ID)
);
