-- TABLE: TEMP.JUSDAVIS.BKMNG_CONTRACT_REVENUE  |  created: 2026-04-04 02:22:37.443000+00:00

create or replace TABLE BKMNG_CONTRACT_REVENUE (
	ACCOUNT_ID VARCHAR(16777216),
	ACCOUNT_NAME VARCHAR(16777216),
	CONTRACT_START_DATE DATE,
	CONTRACT_END_DATE DATE,
	CONTRACT_CAPACITY FLOAT,
	TOTAL_CONSUMED_REVENUE FLOAT,
	CAPACITY_REMAINING FLOAT,
	TOTAL_CONSUMED_CREDITS FLOAT,
	PREDICTED_OVERAGE_DATE DATE,
	LAST_ACTUAL_DATE DATE,
	REFRESHED_AT TIMESTAMP_NTZ(9)
);
