-- TABLE: TEMP.JUSDAVIS.BKMNG_MEETING_ACTIVITY  |  created: 2026-04-08 01:24:27.664000+00:00

create or replace TABLE BKMNG_MEETING_ACTIVITY (
	ACTIVITY_ID VARCHAR(255) NOT NULL,
	ACCOUNT_ID VARCHAR(40) NOT NULL,
	ACCOUNT_NAME VARCHAR(255),
	ACE_ASSIGNED VARCHAR(255),
	SUBJECT VARCHAR(4000),
	ACTIVITY_DATE DATE,
	OWNER_ID VARCHAR(40),
	PARTICIPANT_NAMES VARCHAR(16000),
	IS_UPCOMING BOOLEAN DEFAULT FALSE,
	TAKEAWAYS VARCHAR(65535),
	IS_PAIN_POINTS BOOLEAN DEFAULT FALSE,
	IS_NEXT_STEPS BOOLEAN DEFAULT FALSE,
	IS_COMPETITOR BOOLEAN DEFAULT FALSE,
	REFRESHED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
