-- TABLE: TEMP.JUSDAVIS.BKMNG_USE_CASE_BREAKDOWNS  |  created: 2026-04-15 21:03:54.636000+00:00

create or replace TABLE BKMNG_USE_CASE_BREAKDOWNS (
	BREAKDOWN_ID VARCHAR(64) NOT NULL,
	USE_CASE_ID VARCHAR(18) NOT NULL,
	ACCOUNT_ID VARCHAR(18) NOT NULL,
	ACCOUNT_NAME VARCHAR(500),
	PARENT_USE_CASE_NAME VARCHAR(1000),
	SPLITTABILITY_SCORE FLOAT,
	SPLITTABILITY_REASON VARCHAR(4000),
	SUB_USE_CASE_INDEX NUMBER(38,0),
	SUB_USE_CASE_NAME VARCHAR(1000),
	SUB_WORKLOAD VARCHAR(500),
	SUB_TECHNICAL_USE_CASE VARCHAR(500),
	SUB_RATIONALE VARCHAR(4000),
	SUB_ESTIMATED_EFFORT VARCHAR(500),
	SUB_KEY_ACTIVITIES VARCHAR(8000),
	TOTAL_SUB_USE_CASES NUMBER(38,0),
	OVERALL_RATIONALE VARCHAR(8000),
	CRITERIA_SCORES VARCHAR(8000),
	STATUS VARCHAR(20) DEFAULT 'suggested',
	COMPUTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	REFRESHED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	SUB_DEPENDENCY_INDEX NUMBER(38,0),
	SUB_ESTIMATED_DAYS NUMBER(38,0),
	primary key (BREAKDOWN_ID)
);
