-- TABLE: TEMP.JUSDAVIS.BKMNG_USER_ALERT_PREFERENCES  |  created: 2026-04-15 20:15:53.605000+00:00

create or replace TABLE BKMNG_USER_ALERT_PREFERENCES (
	USER_EMAIL VARCHAR(16777216) NOT NULL WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='EMAIL'),
	SIGNAL_TYPE VARCHAR(16777216) NOT NULL,
	ENABLED BOOLEAN DEFAULT TRUE,
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	PRIORITY_OVERRIDE VARCHAR(16777216),
	primary key (USER_EMAIL, SIGNAL_TYPE)
);
