-- TABLE: TEMP.JUSDAVIS.BKMNG_AI_USE_CASE_ASSESSMENTS  |  created: 2026-04-07 23:56:59.859000+00:00

create or replace TABLE BKMNG_AI_USE_CASE_ASSESSMENTS (
	USE_CASE_ID VARCHAR(50) NOT NULL,
	ACCOUNT_ID VARCHAR(50) NOT NULL,
	ACCOUNT_NAME VARCHAR(255),
	USE_CASE_NAME VARCHAR(500),
	AI_TIER VARCHAR(20),
	CONFIDENCE FLOAT,
	RATIONALE VARCHAR(16777216),
	RECOMMENDED_ACTIONS VARCHAR(16777216),
	RISK_LEVEL VARCHAR(20),
	OPPORTUNITY_SCORE FLOAT,
	COMPUTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	REFRESHED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (USE_CASE_ID)
);
