-- TABLE: TEMP.JUSDAVIS.BKMNG_USE_CASE_NOTES  |  created: 2026-04-07 16:13:25.191000+00:00

create or replace TABLE BKMNG_USE_CASE_NOTES (
	NOTE_ID VARCHAR(64),
	USE_CASE_ID VARCHAR(18),
	ACCOUNT_ID VARCHAR(18),
	ACCOUNT_NAME VARCHAR(255),
	USE_CASE_NAME VARCHAR(255),
	LEAD_SE VARCHAR(255) WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='EMAIL'),
	NOTE_DATE DATE,
	AUTHOR_INITIALS VARCHAR(30),
	CONTENT VARCHAR(8000),
	REFRESHED_AT TIMESTAMP_NTZ(9)
);
