-- TABLE: TEMP.JUSDAVIS.BKMNG_ACEM_TEAM  |  created: 2026-04-04 06:11:39.530000+00:00

create or replace TABLE BKMNG_ACEM_TEAM (
	ACEM_EMAIL VARCHAR(16777216) NOT NULL WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='EMAIL'),
	ACE_EMAIL VARCHAR(16777216) NOT NULL WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='EMAIL'),
	REFRESHED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
