-- TABLE: TEMP.JUSDAVIS.BKMNG_CONSUMPTION_TRENDS  |  created: 2026-04-04 02:26:16.638000+00:00

create or replace TABLE BKMNG_CONSUMPTION_TRENDS (
	ACCOUNT_ID VARCHAR(16777216),
	PERIOD_TYPE VARCHAR(16777216),
	PERIOD_START DATE,
	PERIOD_REVENUE FLOAT,
	PERIOD_CREDITS FLOAT,
	DAYS_IN_PERIOD NUMBER(38,0),
	IS_COMPLETE_PERIOD BOOLEAN,
	PREV_PERIOD_REVENUE FLOAT,
	PCT_CHANGE FLOAT,
	ROLLING_4_PERIOD_AVG_REVENUE FLOAT,
	PREV_ROLLING_4_PERIOD_AVG_REVENUE FLOAT,
	ROLLING_PCT_CHANGE FLOAT,
	REFRESHED_AT TIMESTAMP_NTZ(9)
);
