-- TABLE: TEMP.JUSDAVIS.BKMNG_USER_PREFERENCES  |  created: 2026-04-15 17:41:31.572000+00:00

create or replace TABLE BKMNG_USER_PREFERENCES (
	USER_EMAIL VARCHAR(16777216) NOT NULL WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='EMAIL'),
	PREFERRED_NAME VARCHAR(16777216) WITH TAG (SNOWFLAKE.CORE.PRIVACY_CATEGORY='IDENTIFIER', SNOWFLAKE.CORE.SEMANTIC_CATEGORY='NAME'),
	GREETING_STYLE VARCHAR(16777216) DEFAULT 'Hi [Name],',
	CLOSING_STYLE VARCHAR(16777216) DEFAULT 'Best, ACE',
	WRITING_EXAMPLES VARIANT,
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (USER_EMAIL)
);
